// lib/engine/allergenVocabulary.ts
// Weighted allergen vocabulary for direct + synonym detection.
// Each entry maps a term (exact substring match after normalization) to one
// or more allergens plus the signal source that produced it.

import type { AllergenId, SignalSource } from "./types";

export type VocabEntry = {
  term: string;
  allergens: AllergenId[];
  source: SignalSource;
  note?: string;
};

export const ALLERGEN_VOCABULARY: VocabEntry[] = [
  // ─── DAIRY ─────────────────────────────────────────────────────────────────
  { term: "milk",            allergens: ["dairy"],         source: "direct" },
  { term: "butter",          allergens: ["dairy"],         source: "direct" },
  { term: "cheese",          allergens: ["dairy"],         source: "direct" },
  { term: "cream",           allergens: ["dairy"],         source: "direct" },
  { term: "whey",            allergens: ["dairy"],         source: "direct" },
  { term: "casein",          allergens: ["dairy"],         source: "synonym", note: "Milk protein" },
  { term: "yogurt",          allergens: ["dairy"],         source: "direct" },
  { term: "yoghurt",         allergens: ["dairy"],         source: "direct" },
  { term: "ghee",            allergens: ["dairy"],         source: "direct", note: "Clarified butter" },
  { term: "lactose",         allergens: ["dairy"],         source: "synonym" },
  { term: "lactalbumin",     allergens: ["dairy"],         source: "synonym" },
  { term: "creme",           allergens: ["dairy"],         source: "direct" },
  { term: "beurre",          allergens: ["dairy"],         source: "synonym", note: "French: butter" },
  { term: "fromage",         allergens: ["dairy"],         source: "synonym", note: "French: cheese" },
  { term: "gratin",          allergens: ["dairy"],         source: "dish",    note: "Au gratin = cheese sauce" },
  { term: "bechamel",        allergens: ["dairy", "wheat"], source: "sauce",  note: "White sauce" },
  { term: "hollandaise",     allergens: ["dairy", "egg"],  source: "sauce",   note: "Butter + egg yolk sauce" },
  { term: "mornay",          allergens: ["dairy", "wheat"], source: "sauce",  note: "Béchamel + cheese" },
  { term: "alfredo",         allergens: ["dairy"],         source: "dish",    note: "Cream + parmesan sauce" },
  { term: "carbonara",       allergens: ["dairy", "egg"],  source: "dish",    note: "Cream/egg + cheese sauce" },
  { term: "ricotta",         allergens: ["dairy"],         source: "direct" },
  { term: "mozzarella",      allergens: ["dairy"],         source: "direct" },
  { term: "parmesan",        allergens: ["dairy"],         source: "direct" },
  { term: "cheddar",         allergens: ["dairy"],         source: "direct" },
  { term: "brie",            allergens: ["dairy"],         source: "direct" },
  { term: "feta",            allergens: ["dairy"],         source: "direct" },
  { term: "gouda",           allergens: ["dairy"],         source: "direct" },
  { term: "provolone",       allergens: ["dairy"],         source: "direct" },
  { term: "gorgonzola",      allergens: ["dairy"],         source: "direct" },
  { term: "blue cheese",     allergens: ["dairy"],         source: "direct" },
  { term: "ranch",           allergens: ["dairy", "egg"],  source: "sauce",   note: "Buttermilk + mayo base" },
  { term: "ice cream",       allergens: ["dairy"],         source: "direct" },
  { term: "gelato",          allergens: ["dairy"],         source: "direct" },
  { term: "sour cream",      allergens: ["dairy"],         source: "direct" },
  { term: "half and half",   allergens: ["dairy"],         source: "direct" },
  { term: "heavy cream",     allergens: ["dairy"],         source: "direct" },
  { term: "whipped cream",   allergens: ["dairy"],         source: "direct" },
  { term: "milk chocolate",  allergens: ["dairy"],         source: "direct" },
  { term: "latte",           allergens: ["dairy"],         source: "direct", note: "Espresso + steamed milk" },
  { term: "cappuccino",      allergens: ["dairy"],         source: "direct" },
  { term: "macchiato",       allergens: ["dairy"],         source: "direct" },
  { term: "flat white",      allergens: ["dairy"],         source: "direct" },
  { term: "mascarpone",      allergens: ["dairy"],         source: "direct" },
  { term: "cream cheese",    allergens: ["dairy"],         source: "direct" },
  { term: "paneer",          allergens: ["dairy"],         source: "direct", note: "Indian fresh cheese" },
  { term: "halloumi",        allergens: ["dairy"],         source: "direct" },
  { term: "burrata",         allergens: ["dairy"],         source: "direct" },
  { term: "creme fraiche",   allergens: ["dairy"],         source: "direct" },
  { term: "crème fraîche",   allergens: ["dairy"],         source: "direct" },
  { term: "buttermilk",      allergens: ["dairy"],         source: "direct" },
  { term: "gruyere",         allergens: ["dairy"],         source: "direct" },
  { term: "gruyère",         allergens: ["dairy"],         source: "direct" },
  { term: "manchego",        allergens: ["dairy"],         source: "direct" },
  { term: "camembert",       allergens: ["dairy"],         source: "direct" },
  { term: "cotija",          allergens: ["dairy"],         source: "direct" },
  { term: "pecorino",        allergens: ["dairy"],         source: "direct" },
  { term: "havarti",         allergens: ["dairy"],         source: "direct" },
  { term: "fontina",         allergens: ["dairy"],         source: "direct" },
  { term: "queso fresco",    allergens: ["dairy"],         source: "direct" },
  { term: "beurre blanc",    allergens: ["dairy"],         source: "sauce",  note: "French butter sauce (butter + white wine)" },
  { term: "buffalo sauce",   allergens: ["dairy"],         source: "sauce",  note: "Hot sauce + butter emulsion" },
  { term: "au poivre",       allergens: ["dairy"],         source: "sauce",  note: "Cream + peppercorn sauce" },
  { term: "tikka masala",    allergens: ["dairy"],         source: "dish",   note: "Creamy tomato-butter-cream sauce" },
  { term: "chowder",         allergens: ["dairy"],         source: "dish",   note: "New England chowder uses heavy cream; Manhattan style does not" },
  { term: "clam chowder",    allergens: ["dairy", "shellfish"], source: "dish" },
  { term: "fondue",          allergens: ["dairy"],         source: "direct", note: "Melted cheese dish" },
  { term: "queso",           allergens: ["dairy"],         source: "direct", note: "Mexican melted cheese dip/sauce" },
  { term: "tzatziki",        allergens: ["dairy"],         source: "direct", note: "Greek yogurt and cucumber sauce" },
  { term: "raita",           allergens: ["dairy"],         source: "direct", note: "Indian yogurt-based condiment" },
  { term: "condensed milk",  allergens: ["dairy"],         source: "direct" },
  { term: "evaporated milk", allergens: ["dairy"],         source: "direct" },
  { term: "milk powder",     allergens: ["dairy"],         source: "synonym" },
  { term: "dry milk",        allergens: ["dairy"],         source: "synonym" },
  { term: "kheer",           allergens: ["dairy"],         source: "dish",   note: "Indian rice pudding made with milk" },
  { term: "kulfi",           allergens: ["dairy"],         source: "dish",   note: "Indian frozen dairy dessert" },

  // ─── EGG ───────────────────────────────────────────────────────────────────
  { term: "egg",             allergens: ["egg"],           source: "direct" },
  { term: "mayo",            allergens: ["egg"],           source: "direct" },
  { term: "mayonnaise",      allergens: ["egg"],           source: "direct" },
  { term: "aioli",           allergens: ["egg"],           source: "synonym", note: "Mayo-based" },
  { term: "meringue",        allergens: ["egg"],           source: "direct" },
  { term: "custard",         allergens: ["egg", "dairy"],  source: "direct" },
  { term: "frittata",        allergens: ["egg"],           source: "direct" },
  { term: "quiche",          allergens: ["egg", "dairy", "wheat"], source: "dish" },
  { term: "souffle",         allergens: ["egg", "dairy"],  source: "dish" },
  { term: "eggnog",          allergens: ["egg", "dairy"],  source: "direct" },
  { term: "lecithin",        allergens: ["egg", "soy"],    source: "synonym", note: "Often egg or soy derived" },
  { term: "albumen",         allergens: ["egg"],           source: "synonym", note: "Egg white" },
  { term: "ovalbumin",       allergens: ["egg"],           source: "synonym" },
  { term: "ovomucin",        allergens: ["egg"],           source: "synonym" },
  { term: "livetin",         allergens: ["egg"],           source: "synonym" },
  { term: "globulin",        allergens: ["egg"],           source: "synonym" },
  { term: "egg wash",        allergens: ["egg"],           source: "prep",    note: "Brushed on baked goods/breaded items" },
  { term: "deviled",         allergens: ["egg"],           source: "dish",    note: "Deviled eggs" },
  { term: "benedict",        allergens: ["egg", "dairy"],  source: "dish",    note: "Eggs Benedict = poached egg + hollandaise" },
  { term: "omelet",          allergens: ["egg"],           source: "direct" },
  { term: "omelette",        allergens: ["egg"],           source: "direct" },
  { term: "egg salad",       allergens: ["egg"],           source: "dish" },
  { term: "scotch egg",      allergens: ["egg", "wheat", "gluten"], source: "dish", note: "Hard-boiled egg in sausage + breadcrumbs" },
  { term: "shakshuka",       allergens: ["egg"],           source: "dish",    note: "Eggs poached in tomato sauce" },
  { term: "brioche",         allergens: ["wheat", "gluten", "egg", "dairy"], source: "dish" },
  { term: "croissant",       allergens: ["wheat", "gluten", "dairy", "egg"], source: "dish" },
  { term: "waffle",          allergens: ["wheat", "gluten", "egg", "dairy"], source: "dish" },
  { term: "pancake",         allergens: ["wheat", "gluten", "egg", "dairy"], source: "dish" },
  { term: "french toast",    allergens: ["wheat", "gluten", "egg", "dairy"], source: "dish" },
  { term: "loco moco",       allergens: ["egg"],           source: "dish",   note: "Hawaiian rice bowl topped with a fried egg and gravy" },
  { term: "huevos rancheros", allergens: ["egg", "corn"],  source: "dish",   note: "Fried eggs on corn tortillas" },
  { term: "eggs benedict",   allergens: ["egg", "dairy", "wheat", "gluten"], source: "dish", note: "Poached eggs on an English muffin with hollandaise" },
  { term: "stracciatella",   allergens: ["egg", "dairy"],  source: "dish",   note: "Italian egg-drop soup or egg-ribbon dish" },

  // ─── SOY ───────────────────────────────────────────────────────────────────
  { term: "soy sauce",       allergens: ["soy", "wheat", "gluten"], source: "direct" },
  { term: "soy",             allergens: ["soy"],           source: "direct" },
  { term: "tofu",            allergens: ["soy"],           source: "direct" },
  { term: "miso",            allergens: ["soy"],           source: "direct" },
  { term: "edamame",         allergens: ["soy"],           source: "direct" },
  { term: "tempeh",          allergens: ["soy"],           source: "direct" },
  { term: "tamari",          allergens: ["soy"],           source: "direct" },
  { term: "natto",           allergens: ["soy"],           source: "direct" },
  { term: "shoyu",           allergens: ["soy", "wheat", "gluten"], source: "synonym", note: "Japanese soy sauce" },
  { term: "ponzu",           allergens: ["soy", "fish"],   source: "sauce",   note: "Soy + citrus + dashi" },
  { term: "hoisin",          allergens: ["soy", "wheat", "gluten"], source: "sauce" },
  { term: "teriyaki",        allergens: ["soy", "wheat", "gluten"], source: "sauce" },
  { term: "yakitori",        allergens: ["soy", "wheat", "gluten"], source: "dish", note: "Teriyaki-glazed chicken" },
  { term: "gyoza",           allergens: ["wheat", "gluten", "soy"], source: "dish" },
  { term: "dumpling",        allergens: ["wheat", "gluten", "soy"], source: "dish" },
  { term: "edamame",         allergens: ["soy"],           source: "direct" },

  // ─── WHEAT / GLUTEN ────────────────────────────────────────────────────────
  { term: "bulgogi",         allergens: ["soy", "wheat", "gluten", "sesame"], source: "dish", note: "Korean marinated beef — soy + sesame marinade" },
  { term: "flour",           allergens: ["wheat", "gluten"], source: "direct" },
  { term: "bread",           allergens: ["wheat", "gluten"], source: "direct" },
  { term: "bun",             allergens: ["wheat", "gluten"], source: "direct" },
  { term: "gluten",          allergens: ["gluten", "wheat"], source: "direct" },
  { term: "barley",          allergens: ["gluten"],         source: "direct" },
  { term: "rye",             allergens: ["gluten"],         source: "direct" },
  { term: "pasta",           allergens: ["wheat", "gluten"], source: "direct" },
  { term: "noodle",          allergens: ["wheat", "gluten"], source: "direct" },
  { term: "crouton",         allergens: ["wheat", "gluten"], source: "direct" },
  { term: "tortilla",        allergens: ["wheat", "gluten", "corn"], source: "direct", note: "Tortillas may be flour (wheat) or corn — both flagged for safety" },
  { term: "pretzel",         allergens: ["wheat", "gluten"], source: "direct" },
  { term: "pita",            allergens: ["wheat", "gluten"], source: "direct" },
  { term: "wrap",            allergens: ["wheat", "gluten"], source: "direct" },
  { term: "sandwich",        allergens: ["wheat", "gluten"], source: "direct" },
  { term: "sub",             allergens: ["wheat", "gluten"], source: "direct" },
  { term: "roll",            allergens: ["wheat", "gluten"], source: "direct" },
  { term: "crust",           allergens: ["wheat", "gluten"], source: "direct" },
  { term: "breaded",         allergens: ["wheat", "gluten"], source: "prep" },
  { term: "battered",        allergens: ["wheat", "gluten", "egg"], source: "prep" },
  { term: "tempura",         allergens: ["wheat", "gluten", "egg"], source: "dish" },
  { term: "panko",           allergens: ["wheat", "gluten"], source: "direct", note: "Japanese breadcrumbs" },
  { term: "breadcrumb",      allergens: ["wheat", "gluten"], source: "direct" },
  { term: "semolina",        allergens: ["wheat", "gluten"], source: "direct" },
  { term: "spelt",           allergens: ["wheat", "gluten"], source: "direct" },
  { term: "kamut",           allergens: ["wheat", "gluten"], source: "direct" },
  { term: "farro",           allergens: ["wheat", "gluten"], source: "direct" },
  { term: "bulgur",          allergens: ["wheat", "gluten"], source: "direct" },
  { term: "couscous",        allergens: ["wheat", "gluten"], source: "direct" },
  { term: "seitan",          allergens: ["wheat", "gluten"], source: "direct", note: "Pure wheat gluten" },
  { term: "pizza",           allergens: ["wheat", "gluten", "dairy"], source: "dish" },
  { term: "calzone",         allergens: ["wheat", "gluten", "dairy"], source: "dish" },
  { term: "stromboli",       allergens: ["wheat", "gluten", "dairy"], source: "dish" },
  { term: "ramen",           allergens: ["wheat", "gluten", "soy"],   source: "dish" },
  { term: "udon",            allergens: ["wheat", "gluten"],          source: "dish" },
  { term: "lo mein",         allergens: ["wheat", "gluten", "soy"],   source: "dish" },
  { term: "chow mein",       allergens: ["wheat", "gluten", "soy"],   source: "dish" },
  { term: "malt",            allergens: ["gluten"],         source: "direct", note: "Barley malt" },
  { term: "malt vinegar",    allergens: ["gluten"],         source: "direct" },
  { term: "schnitzel",       allergens: ["wheat", "gluten", "egg"], source: "dish", note: "Thin breaded cutlet (flour + egg + breadcrumbs)" },
  { term: "katsu",           allergens: ["wheat", "gluten", "egg"], source: "dish", note: "Japanese panko-breaded cutlet" },
  { term: "tonkatsu",        allergens: ["wheat", "gluten", "egg"], source: "dish", note: "Japanese pork cutlet in panko" },
  { term: "milanese",        allergens: ["wheat", "gluten", "egg"], source: "dish", note: "Milanese = breaded + pan-fried in butter" },
  { term: "croquette",       allergens: ["wheat", "gluten", "egg", "dairy"], source: "dish", note: "Breaded + fried, often with béchamel filling" },
  { term: "bruschetta",      allergens: ["wheat", "gluten"], source: "dish",  note: "Toasted/grilled bread" },
  { term: "garlic bread",    allergens: ["wheat", "gluten", "dairy"], source: "dish" },
  { term: "garlic toast",    allergens: ["wheat", "gluten", "dairy"], source: "dish" },
  { term: "meatball",        allergens: ["wheat", "gluten", "egg"], source: "dish", note: "Typically bound with breadcrumbs and egg" },
  { term: "meatballs",       allergens: ["wheat", "gluten", "egg"], source: "dish" },
  { term: "meat loaf",       allergens: ["wheat", "gluten", "egg"], source: "dish", note: "Bound with breadcrumbs and egg" },
  { term: "meatloaf",        allergens: ["wheat", "gluten", "egg"], source: "dish" },
  { term: "fried chicken",   allergens: ["wheat", "gluten", "egg"], source: "dish", note: "Typically dredged in flour + egg wash" },
  { term: "pot pie",         allergens: ["wheat", "gluten", "dairy", "egg"], source: "dish", note: "Pastry crust + cream sauce filling" },
  { term: "fish and chips",  allergens: ["wheat", "gluten", "egg", "fish"], source: "dish", note: "Battered fish + fried in shared oil" },
  { term: "fish n chips",    allergens: ["wheat", "gluten", "egg", "fish"], source: "dish" },
  { term: "wonton",          allergens: ["wheat", "gluten", "egg"],         source: "dish", note: "Wheat-and-egg wrappers" },
  { term: "egg roll",        allergens: ["wheat", "gluten", "egg"],         source: "dish", note: "Crispy wheat-and-egg wrapper" },
  { term: "eggroll",         allergens: ["wheat", "gluten", "egg"],         source: "dish" },
  { term: "spring roll",     allergens: ["wheat", "gluten"],                source: "dish", note: "Fried spring rolls use wheat wrappers (rice paper rolls are gluten-free — verify)" },
  { term: "bao bun",         allergens: ["wheat", "gluten"],                source: "dish", note: "Steamed Chinese bun made from wheat flour" },
  { term: "steamed bun",     allergens: ["wheat", "gluten"],                source: "dish" },
  { term: "baozi",           allergens: ["wheat", "gluten"],                source: "dish" },
  { term: "empanada",        allergens: ["wheat", "gluten"],                source: "dish", note: "Latin pastry turnover with a wheat flour dough" },
  { term: "samosa",          allergens: ["wheat", "gluten"],                source: "dish", note: "South Asian fried pastry with wheat flour dough" },
  { term: "naan",            allergens: ["wheat", "gluten", "dairy"],       source: "dish", note: "Indian flatbread made with flour and often yogurt or butter" },
  { term: "roti",            allergens: ["wheat", "gluten"],                source: "dish", note: "South Asian flatbread made with whole wheat flour" },
  { term: "chapati",         allergens: ["wheat", "gluten"],                source: "dish" },
  { term: "paratha",         allergens: ["wheat", "gluten", "dairy"],       source: "dish", note: "Layered Indian flatbread cooked in ghee or butter" },
  { term: "puri",            allergens: ["wheat", "gluten"],                source: "dish", note: "Deep-fried Indian wheat bread" },
  { term: "orzo",            allergens: ["wheat", "gluten"],                source: "direct", note: "Rice-shaped wheat pasta — often mistaken for rice" },
  { term: "phyllo",          allergens: ["wheat", "gluten"],                source: "direct", note: "Thin wheat pastry dough" },
  { term: "filo",            allergens: ["wheat", "gluten"],                source: "direct" },
  { term: "puff pastry",     allergens: ["wheat", "gluten", "dairy"],       source: "direct", note: "Laminated wheat dough with layers of butter" },
  { term: "shortbread",      allergens: ["wheat", "gluten", "dairy"],       source: "direct", note: "Butter-and-flour biscuit" },
  { term: "biscuit",         allergens: ["wheat", "gluten", "dairy"],       source: "direct", note: "American-style biscuit uses flour and butter" },
  { term: "sourdough",       allergens: ["wheat", "gluten"],                source: "direct" },
  { term: "ciabatta",        allergens: ["wheat", "gluten"],                source: "direct" },
  { term: "focaccia",        allergens: ["wheat", "gluten"],                source: "direct" },
  { term: "challah",         allergens: ["wheat", "gluten", "egg"],         source: "dish",   note: "Jewish braided bread made with eggs and flour" },
  { term: "hoagie",          allergens: ["wheat", "gluten"],                source: "direct", note: "Sub-style wheat roll" },
  { term: "slider",          allergens: ["wheat", "gluten"],                source: "direct", note: "Mini burger on a wheat bun" },
  { term: "corn dog",        allergens: ["wheat", "gluten", "egg", "corn"], source: "dish",   note: "Hot dog in a wheat-and-cornmeal batter" },
  { term: "chicken nugget",  allergens: ["wheat", "gluten", "egg"],         source: "dish",   note: "Breaded/battered chicken — flour and egg coating" },
  { term: "chicken tender",  allergens: ["wheat", "gluten", "egg"],         source: "dish",   note: "Breaded/battered chicken strip" },
  { term: "chicken finger",  allergens: ["wheat", "gluten", "egg"],         source: "dish" },
  { term: "chicken strip",   allergens: ["wheat", "gluten", "egg"],         source: "dish" },
  { term: "onion ring",      allergens: ["wheat", "gluten", "egg"],         source: "dish",   note: "Battered and fried in a wheat-egg batter" },
  { term: "onion rings",     allergens: ["wheat", "gluten", "egg"],         source: "dish" },
  { term: "jalapeño popper", allergens: ["wheat", "gluten", "egg", "dairy"], source: "dish",  note: "Cream cheese-stuffed jalapeño in a wheat-egg batter" },
  { term: "jalapeno popper", allergens: ["wheat", "gluten", "egg", "dairy"], source: "dish" },
  { term: "donut",           allergens: ["wheat", "gluten", "egg", "dairy"], source: "dish",  note: "Deep-fried wheat dough with egg and dairy" },
  { term: "doughnut",        allergens: ["wheat", "gluten", "egg", "dairy"], source: "dish" },
  { term: "churro",          allergens: ["wheat", "gluten", "egg"],          source: "dish",  note: "Fried choux pastry made with wheat flour and egg" },
  { term: "beignet",         allergens: ["wheat", "gluten", "egg", "dairy"], source: "dish",  note: "New Orleans fried dough made with wheat, egg, and milk" },
  { term: "crepe",           allergens: ["wheat", "gluten", "egg", "dairy"], source: "dish",  note: "Thin French pancake made with flour, egg, and milk" },
  { term: "crêpe",           allergens: ["wheat", "gluten", "egg", "dairy"], source: "dish" },
  { term: "eclair",          allergens: ["wheat", "gluten", "egg", "dairy"], source: "dish",  note: "Choux pastry filled with cream" },
  { term: "éclair",          allergens: ["wheat", "gluten", "egg", "dairy"], source: "dish" },
  { term: "profiterole",     allergens: ["wheat", "gluten", "egg", "dairy"], source: "dish",  note: "Choux pastry ball filled with cream" },
  { term: "pierogi",         allergens: ["wheat", "gluten", "egg", "dairy"], source: "dish",  note: "Eastern European wheat-dough dumpling often filled with cheese/potato" },
  { term: "perogies",        allergens: ["wheat", "gluten", "egg", "dairy"], source: "dish" },
  { term: "gnocchi",         allergens: ["wheat", "gluten", "egg"],          source: "dish",  note: "Italian potato dumplings typically contain wheat flour and egg" },
  { term: "strudel",         allergens: ["wheat", "gluten", "dairy"],        source: "dish",  note: "Thin pastry dough (filo/strudel dough) with butter" },
  { term: "english muffin",  allergens: ["wheat", "gluten"],                 source: "direct" },
  { term: "kaiser roll",     allergens: ["wheat", "gluten", "sesame"],       source: "direct", note: "Wheat roll often topped with sesame or poppy seeds" },

  // ─── FISH ──────────────────────────────────────────────────────────────────
  { term: "fish sauce",      allergens: ["fish"],           source: "direct" },
  { term: "worcestershire",  allergens: ["fish"],           source: "synonym", note: "Typically contains anchovies" },
  { term: "anchovy",         allergens: ["fish"],           source: "direct" },
  { term: "anchovies",       allergens: ["fish"],           source: "direct" },
  { term: "salmon",          allergens: ["fish"],           source: "direct" },
  { term: "tuna",            allergens: ["fish"],           source: "direct" },
  { term: "cod",             allergens: ["fish"],           source: "direct" },
  { term: "tilapia",         allergens: ["fish"],           source: "direct" },
  { term: "halibut",         allergens: ["fish"],           source: "direct" },
  { term: "mahi",            allergens: ["fish"],           source: "direct" },
  { term: "mahi mahi",       allergens: ["fish"],           source: "direct" },
  { term: "snapper",         allergens: ["fish"],           source: "direct" },
  { term: "bass",            allergens: ["fish"],           source: "direct" },
  { term: "flounder",        allergens: ["fish"],           source: "direct" },
  { term: "sole",            allergens: ["fish"],           source: "direct" },
  { term: "catfish",         allergens: ["fish"],           source: "direct" },
  { term: "trout",           allergens: ["fish"],           source: "direct" },
  { term: "herring",         allergens: ["fish"],           source: "direct" },
  { term: "sardine",         allergens: ["fish"],           source: "direct" },
  { term: "mackerel",        allergens: ["fish"],           source: "direct" },
  { term: "swordfish",       allergens: ["fish"],           source: "direct" },
  { term: "dashi",           allergens: ["fish"],           source: "synonym", note: "Japanese stock made from bonito/kelp" },
  { term: "bonito",          allergens: ["fish"],           source: "direct" },
  { term: "katsuobushi",     allergens: ["fish"],           source: "direct", note: "Dried bonito flakes" },
  { term: "caesar",          allergens: ["fish", "egg", "dairy"], source: "dish", note: "Traditional Caesar = anchovy + egg + parmesan" },
  { term: "nicoise",         allergens: ["fish"],           source: "dish",   note: "Salade niçoise contains tuna/anchovies" },
  { term: "ahi",             allergens: ["fish"],           source: "direct", note: "Yellowfin/bigeye tuna" },
  { term: "branzino",        allergens: ["fish"],           source: "direct" },
  { term: "grouper",         allergens: ["fish"],           source: "direct" },
  { term: "yellowfin",       allergens: ["fish"],           source: "direct" },
  { term: "bluefin",         allergens: ["fish"],           source: "direct" },
  { term: "pompano",         allergens: ["fish"],           source: "direct" },
  { term: "wahoo",           allergens: ["fish"],           source: "direct" },
  { term: "perch",           allergens: ["fish"],           source: "direct" },
  { term: "ceviche",         allergens: ["fish", "shellfish"], source: "dish", note: "Raw seafood cured in citrus" },
  { term: "surimi",          allergens: ["fish", "shellfish"], source: "direct", note: "Imitation crab made from pollock + shellfish extract" },
  { term: "imitation crab",  allergens: ["fish", "shellfish", "wheat", "gluten"], source: "direct" },
  { term: "kani",            allergens: ["fish", "shellfish"], source: "direct", note: "Japanese imitation crab (surimi)" },
  { term: "lox",             allergens: ["fish"],           source: "direct", note: "Cured/smoked salmon" },
  { term: "gravlax",         allergens: ["fish"],           source: "direct", note: "Scandinavian cured salmon" },
  { term: "arctic char",     allergens: ["fish"],           source: "direct" },
  { term: "steelhead",       allergens: ["fish"],           source: "direct", note: "Trout/salmon species" },
  { term: "albacore",        allergens: ["fish"],           source: "direct", note: "Type of tuna" },
  { term: "sockeye",         allergens: ["fish"],           source: "direct", note: "Sockeye salmon" },
  { term: "haddock",         allergens: ["fish"],           source: "direct" },
  { term: "pollock",         allergens: ["fish"],           source: "direct" },
  { term: "pike",            allergens: ["fish"],           source: "direct" },
  { term: "smelt",           allergens: ["fish"],           source: "direct" },
  { term: "roe",             allergens: ["fish"],           source: "direct", note: "Fish eggs (tobiko, masago, ikura, caviar)" },
  { term: "tobiko",          allergens: ["fish"],           source: "direct", note: "Flying fish roe used as sushi topping" },
  { term: "masago",          allergens: ["fish"],           source: "direct", note: "Capelin fish roe" },
  { term: "ikura",           allergens: ["fish"],           source: "direct", note: "Salmon roe" },
  { term: "caviar",          allergens: ["fish"],           source: "direct", note: "Sturgeon or other fish roe" },

  // ─── SHELLFISH ─────────────────────────────────────────────────────────────
  { term: "shrimp",          allergens: ["shellfish"],      source: "direct" },
  { term: "crab",            allergens: ["shellfish"],      source: "direct" },
  { term: "lobster",         allergens: ["shellfish"],      source: "direct" },
  { term: "clam",            allergens: ["shellfish"],      source: "direct" },
  { term: "oyster",          allergens: ["shellfish"],      source: "direct" },
  { term: "scallop",         allergens: ["shellfish"],      source: "direct" },
  { term: "mussel",          allergens: ["shellfish"],      source: "direct" },
  { term: "calamari",        allergens: ["shellfish"],      source: "direct" },
  { term: "squid",           allergens: ["shellfish"],      source: "direct" },
  { term: "octopus",         allergens: ["shellfish"],      source: "direct" },
  { term: "prawn",           allergens: ["shellfish"],      source: "direct" },
  { term: "langoustine",     allergens: ["shellfish"],      source: "direct" },
  { term: "crayfish",        allergens: ["shellfish"],      source: "direct" },
  { term: "seafood",         allergens: ["shellfish", "fish"], source: "direct" },
  { term: "surf and turf",   allergens: ["shellfish"],      source: "dish" },
  { term: "cioppino",        allergens: ["shellfish", "fish"], source: "dish" },
  { term: "bouillabaisse",   allergens: ["shellfish", "fish"], source: "dish" },
  { term: "paella",          allergens: ["shellfish", "fish"], source: "dish" },
  { term: "bisque",          allergens: ["shellfish", "dairy"], source: "dish", note: "Often lobster/shrimp bisque with cream" },
  { term: "poke",            allergens: ["fish", "soy", "sesame"], source: "dish", note: "Raw fish bowl with soy sauce and sesame" },
  { term: "poke bowl",       allergens: ["fish", "soy", "sesame"], source: "dish" },
  { term: "cuttlefish",      allergens: ["shellfish"],      source: "direct" },
  { term: "sea urchin",      allergens: ["shellfish"],      source: "direct", note: "Uni — cross-reactive with shellfish in many allergy profiles" },
  { term: "uni",             allergens: ["shellfish"],      source: "direct", note: "Sea urchin roe" },
  { term: "abalone",         allergens: ["shellfish"],      source: "direct" },
  { term: "conch",           allergens: ["shellfish"],      source: "direct" },
  { term: "barnacle",        allergens: ["shellfish"],      source: "direct" },

  // ─── PEANUT ────────────────────────────────────────────────────────────────
  { term: "peanut butter",   allergens: ["peanut"],         source: "direct" },
  { term: "peanut",          allergens: ["peanut"],         source: "direct" },
  { term: "satay",           allergens: ["peanut"],         source: "dish",   note: "Satay sauce = peanut-based" },
  { term: "pad thai",        allergens: ["peanut", "shellfish", "egg"], source: "dish" },
  { term: "gado gado",       allergens: ["peanut"],         source: "dish" },
  { term: "kung pao",        allergens: ["peanut"],         source: "dish" },
  { term: "groundnut",       allergens: ["peanut"],         source: "synonym" },
  { term: "monkey nuts",     allergens: ["peanut"],         source: "synonym" },
  { term: "peanut oil",      allergens: ["peanut"],         source: "direct" },
  { term: "arachis oil",     allergens: ["peanut"],         source: "synonym", note: "Peanut oil (scientific name)" },
  { term: "peanut sauce",    allergens: ["peanut"],         source: "direct" },
  { term: "thai peanut",     allergens: ["peanut"],         source: "direct" },
  { term: "boiled peanut",   allergens: ["peanut"],         source: "direct" },

  // ─── TREE NUT ──────────────────────────────────────────────────────────────
  { term: "pine nut",        allergens: ["tree-nut"],       source: "direct" },
  { term: "almond",          allergens: ["tree-nut"],       source: "direct" },
  { term: "walnut",          allergens: ["tree-nut"],       source: "direct" },
  { term: "cashew",          allergens: ["tree-nut"],       source: "direct" },
  { term: "pecan",           allergens: ["tree-nut"],       source: "direct" },
  { term: "pistachio",       allergens: ["tree-nut"],       source: "direct" },
  { term: "hazelnut",        allergens: ["tree-nut"],       source: "direct" },
  { term: "macadamia",       allergens: ["tree-nut"],       source: "direct" },
  { term: "chestnut",        allergens: ["tree-nut"],       source: "direct" },
  { term: "brazil nut",      allergens: ["tree-nut"],       source: "direct" },
  { term: "coconut",         allergens: ["tree-nut"],       source: "direct", note: "FDA classifies as tree nut" },
  { term: "pesto",           allergens: ["tree-nut", "dairy"], source: "sauce", note: "Pine nuts + parmesan" },
  { term: "praline",         allergens: ["tree-nut"],       source: "direct" },
  { term: "marzipan",        allergens: ["tree-nut"],       source: "direct", note: "Almond paste" },
  { term: "frangipane",      allergens: ["tree-nut", "egg", "dairy"], source: "dish" },
  { term: "gianduja",        allergens: ["tree-nut", "dairy"], source: "direct", note: "Chocolate + hazelnut" },
  { term: "nutella",         allergens: ["tree-nut", "dairy"], source: "direct" },
  { term: "nut",             allergens: ["tree-nut"],       source: "direct", note: "Generic nut mention" },
  { term: "nut butter",      allergens: ["tree-nut"],       source: "direct" },
  { term: "trail mix",       allergens: ["tree-nut", "peanut"], source: "dish" },
  { term: "granola",         allergens: ["oats", "tree-nut"], source: "dish" },
  { term: "almond milk",     allergens: ["tree-nut"],       source: "direct" },
  { term: "almond butter",   allergens: ["tree-nut"],       source: "direct" },
  { term: "cashew cream",    allergens: ["tree-nut"],       source: "direct", note: "Common vegan dairy substitute" },
  { term: "walnut oil",      allergens: ["tree-nut"],       source: "direct" },
  { term: "amaretto",        allergens: ["tree-nut"],       source: "direct", note: "Almond-flavored liqueur" },
  { term: "marzipan",        allergens: ["tree-nut"],       source: "direct", note: "Almond paste" },

  // ─── SESAME ────────────────────────────────────────────────────────────────
  { term: "sesame",          allergens: ["sesame"],         source: "direct" },
  { term: "tahini",          allergens: ["sesame"],         source: "direct" },
  { term: "hummus",          allergens: ["sesame", "legumes"], source: "dish", note: "Chickpeas + tahini" },
  { term: "sesame oil",      allergens: ["sesame"],         source: "direct" },
  { term: "sesame seed",     allergens: ["sesame"],         source: "direct" },
  { term: "bagel",           allergens: ["sesame", "wheat", "gluten"], source: "dish", note: "Often has sesame seeds" },
  { term: "gochujang",       allergens: ["sesame", "wheat", "gluten"], source: "sauce" },
  { term: "za atar",         allergens: ["sesame"],         source: "dish",   note: "Spice mix with sesame" },
  { term: "zatar",           allergens: ["sesame"],         source: "dish" },
  { term: "benne",           allergens: ["sesame"],         source: "synonym", note: "African/Southern term for sesame" },
  { term: "black sesame",    allergens: ["sesame"],         source: "direct" },
  { term: "sesame paste",    allergens: ["sesame"],         source: "direct" },
  { term: "halvah",          allergens: ["sesame"],         source: "direct", note: "Middle Eastern confection made from tahini (sesame paste)" },
  { term: "halva",           allergens: ["sesame"],         source: "direct" },
  { term: "furikake",        allergens: ["sesame", "fish"], source: "direct", note: "Japanese seasoning blend with sesame seeds and dried fish" },

  // ─── CORN ──────────────────────────────────────────────────────────────────
  { term: "cornstarch",      allergens: ["corn"],           source: "direct" },
  { term: "corn",            allergens: ["corn"],           source: "direct" },
  { term: "masa",            allergens: ["corn"],           source: "direct" },
  { term: "polenta",         allergens: ["corn"],           source: "direct" },
  { term: "grits",           allergens: ["corn"],           source: "direct" },
  { term: "hominy",          allergens: ["corn"],           source: "direct" },
  { term: "corn tortilla",   allergens: ["corn"],           source: "direct" },
  { term: "tortilla chip",   allergens: ["corn"],           source: "direct", note: "Tortilla chips are made from corn masa" },
  { term: "corn chip",       allergens: ["corn"],           source: "direct" },
  { term: "corn syrup",      allergens: ["corn"],           source: "direct" },
  { term: "popcorn",         allergens: ["corn"],           source: "direct" },

  // ─── MUSTARD ───────────────────────────────────────────────────────────────
  { term: "mustard",         allergens: ["mustard"],        source: "direct" },
  { term: "dijon",           allergens: ["mustard"],        source: "direct" },
  { term: "whole grain mustard", allergens: ["mustard"],    source: "direct" },
  { term: "hot dog mustard", allergens: ["mustard"],        source: "direct" },
  { term: "honey mustard",   allergens: ["mustard"],        source: "direct" },
  { term: "yellow mustard",  allergens: ["mustard"],        source: "direct" },
  { term: "mustard seed",    allergens: ["mustard"],        source: "direct" },
  { term: "mustard oil",     allergens: ["mustard"],        source: "direct" },
  { term: "english mustard", allergens: ["mustard"],        source: "direct" },
  { term: "vinaigrette",     allergens: ["mustard"],        source: "sauce",  note: "Classic vinaigrette uses Dijon mustard as an emulsifier — always ask" },

  // ─── LEGUMES ───────────────────────────────────────────────────────────────
  { term: "lupin",           allergens: ["legumes"],        source: "direct" },
  { term: "lupine",          allergens: ["legumes"],        source: "direct" },
  { term: "fava bean",       allergens: ["legumes"],        source: "direct" },
  { term: "broad bean",      allergens: ["legumes"],        source: "direct" },
  { term: "kidney bean",     allergens: ["legumes"],        source: "direct" },
  { term: "pinto bean",      allergens: ["legumes"],        source: "direct" },
  { term: "black bean",      allergens: ["legumes"],        source: "direct" },
  { term: "chickpea",        allergens: ["legumes"],        source: "direct" },
  { term: "chickpeas",       allergens: ["legumes"],        source: "direct" },
  { term: "lentil",          allergens: ["legumes"],        source: "direct" },
  { term: "lentils",         allergens: ["legumes"],        source: "direct" },
  { term: "dal",             allergens: ["legumes"],        source: "direct", note: "Indian lentil dish" },
  { term: "dhal",            allergens: ["legumes"],        source: "direct" },
  { term: "refried beans",   allergens: ["legumes"],        source: "direct" },
  { term: "bean",            allergens: ["legumes"],        source: "direct" },
  { term: "beans",           allergens: ["legumes"],        source: "direct" },
  { term: "pea",             allergens: ["legumes"],        source: "direct", note: "Peas are legumes" },
  { term: "peas",            allergens: ["legumes"],        source: "direct" },
  { term: "snap pea",        allergens: ["legumes"],        source: "direct" },
  { term: "snap peas",       allergens: ["legumes"],        source: "direct" },
  { term: "snow pea",        allergens: ["legumes"],        source: "direct" },
  { term: "snow peas",       allergens: ["legumes"],        source: "direct" },
  { term: "sugar snap",      allergens: ["legumes"],        source: "direct" },
  { term: "edamame",         allergens: ["legumes", "soy"], source: "direct", note: "Young soybeans — both soy and legume allergen" },
  { term: "falafel",         allergens: ["legumes", "wheat", "gluten"], source: "dish", note: "Chickpea fritters — often contain wheat flour as a binder" },

  // ─── OATS ──────────────────────────────────────────────────────────────────
  { term: "oat",             allergens: ["oats"],           source: "direct" },
  { term: "oats",            allergens: ["oats"],           source: "direct" },
  { term: "oatmeal",         allergens: ["oats"],           source: "direct" },
  { term: "muesli",          allergens: ["oats"],           source: "direct" },

  // ─── MULTI-ALLERGEN DISHES (cross-category) ────────────────────────────────
  { term: "buffalo wing",    allergens: ["dairy", "wheat", "gluten", "egg"], source: "dish", note: "Wing sauce = butter + hot sauce; often breaded" },
  { term: "buffalo wings",   allergens: ["dairy", "wheat", "gluten", "egg"], source: "dish" },
  { term: "chicken wing",    allergens: ["wheat", "gluten", "egg"],           source: "dish", note: "Typically breaded or floured before frying" },
  { term: "poutine",         allergens: ["dairy", "wheat", "gluten"],         source: "dish", note: "Fries + cheese curds + gravy (gravy may contain wheat)" },
  { term: "fried rice",      allergens: ["soy", "egg"],                       source: "dish", note: "Typically made with soy sauce and egg" },
  { term: "crab cake",       allergens: ["shellfish", "wheat", "gluten", "egg", "dairy"], source: "dish", note: "Crab + breadcrumbs + mayo + egg" },
  { term: "crab cakes",      allergens: ["shellfish", "wheat", "gluten", "egg", "dairy"], source: "dish" },
  { term: "lobster roll",    allergens: ["shellfish", "wheat", "gluten", "egg"], source: "dish", note: "Lobster salad in a buttered hot dog bun" },
  { term: "butter chicken",  allergens: ["dairy"],                            source: "dish", note: "Indian curry with cream/butter sauce" },
  { term: "murgh makhani",   allergens: ["dairy"],                            source: "dish", note: "Butter chicken (butter + cream sauce)" },
  { term: "chicken cordon bleu", allergens: ["wheat", "gluten", "egg", "dairy"], source: "dish", note: "Breaded + stuffed with ham and cheese" },
  { term: "shepherd's pie",  allergens: ["dairy", "wheat", "gluten"],         source: "dish", note: "Mashed potato topping with butter; some versions use flour" },
  { term: "shepards pie",    allergens: ["dairy", "wheat", "gluten"],         source: "dish" },
  { term: "cottage pie",     allergens: ["dairy", "wheat", "gluten"],         source: "dish", note: "Same as shepherd's pie but with beef" },
  { term: "moussaka",        allergens: ["dairy", "egg", "wheat", "gluten"],  source: "dish", note: "Béchamel topping (dairy + wheat + egg)" },
  { term: "peking duck",     allergens: ["soy", "wheat", "gluten", "sesame"], source: "dish", note: "Served with hoisin sauce and wheat pancakes" },
  { term: "bread pudding",   allergens: ["wheat", "gluten", "egg", "dairy"],  source: "dish", note: "Stale bread soaked in egg custard" },
  { term: "lava cake",       allergens: ["wheat", "gluten", "egg", "dairy"],  source: "dish", note: "Molten chocolate cake with butter and eggs" },
  { term: "molten cake",     allergens: ["wheat", "gluten", "egg", "dairy"],  source: "dish" },
  { term: "tres leches",     allergens: ["dairy", "egg", "wheat", "gluten"],  source: "dish", note: "Cake soaked in three milks (whole, condensed, evaporated)" },

  // ─── COMMON US RESTAURANT DISHES (additions) ───────────────────────────────
  { term: "quesadilla",      allergens: ["dairy", "wheat", "gluten"],         source: "dish", note: "Flour tortilla grilled with melted cheese" },
  { term: "cheesesteak",     allergens: ["dairy", "wheat", "gluten"],         source: "dish", note: "Sliced beef in a hoagie roll with melted cheese" },
  { term: "cheese steak",    allergens: ["dairy", "wheat", "gluten"],         source: "dish" },
  { term: "philly",          allergens: ["dairy", "wheat", "gluten"],         source: "dish", note: "Philly cheesesteak — roll + melted cheese" },
  { term: "tiramisu",        allergens: ["dairy", "egg", "wheat", "gluten"],  source: "dish", note: "Mascarpone + egg yolks + ladyfinger cookies (wheat)" },
  { term: "cheesecake",      allergens: ["dairy", "egg", "wheat", "gluten"],  source: "dish", note: "Cream cheese filling on a pastry/graham cracker crust" },
  { term: "cannoli",         allergens: ["dairy", "wheat", "gluten"],         source: "dish", note: "Crispy wheat pastry shell filled with ricotta/mascarpone" },
  { term: "baklava",         allergens: ["wheat", "gluten", "tree-nut"],      source: "dish", note: "Phyllo pastry layered with pistachios/walnuts and honey" },
  { term: "spanakopita",     allergens: ["wheat", "gluten", "dairy", "egg"],  source: "dish", note: "Greek spinach pie in phyllo with feta and egg" },
  { term: "nachos",          allergens: ["corn", "dairy"],                    source: "dish", note: "Corn tortilla chips topped with melted cheese" },
  { term: "elote",           allergens: ["corn", "dairy"],                    source: "dish", note: "Mexican street corn topped with crema or cotija cheese" },
  { term: "gulab jamun",     allergens: ["dairy", "wheat", "gluten"],         source: "dish", note: "Indian fried milk-solids dumplings in sugar syrup" },
  { term: "mozzarella stick",allergens: ["dairy", "wheat", "gluten", "egg"],  source: "dish", note: "Breaded mozzarella in a wheat-egg batter" },
  { term: "mozzarella sticks",allergens: ["dairy", "wheat", "gluten", "egg"], source: "dish" },
  { term: "jalapeño popper", allergens: ["dairy", "wheat", "gluten", "egg"],  source: "dish", note: "Cream cheese-stuffed jalapeño in wheat-egg batter" },
  { term: "jalapeno popper", allergens: ["dairy", "wheat", "gluten", "egg"],  source: "dish" },
  { term: "clam chowder",    allergens: ["shellfish", "dairy", "wheat", "gluten"], source: "dish", note: "Shellfish in a cream and flour-thickened broth" },
  { term: "lobster bisque",  allergens: ["shellfish", "dairy", "wheat", "gluten"], source: "dish", note: "Shellfish bisque with cream and roux base" },
  { term: "shrimp scampi",   allergens: ["shellfish", "dairy", "wheat", "gluten"], source: "dish", note: "Shrimp in garlic butter sauce, often served over pasta or with bread" },
  { term: "poke bowl",       allergens: ["fish", "soy", "sesame"],            source: "dish", note: "Raw fish with soy-based sauce and sesame" },
  { term: "bibimbap",        allergens: ["soy", "sesame", "egg"],             source: "dish", note: "Korean rice bowl with gochujang, sesame oil, and often a fried egg" },
  { term: "burrito",         allergens: ["wheat", "gluten", "dairy", "legumes"], source: "dish", note: "Flour tortilla wrapped with beans, cheese, and fillings" },
  { term: "enchilada",       allergens: ["dairy", "corn", "wheat", "gluten"], source: "dish", note: "Corn tortilla (corn) with cheese filling and often a flour-thickened sauce" },
  { term: "tamale",          allergens: ["corn"],                             source: "dish", note: "Corn masa steamed in a corn husk — corn allergen present" },
  { term: "pupusa",          allergens: ["corn", "dairy"],                    source: "dish", note: "Salvadoran stuffed corn masa cake often filled with cheese" },
  { term: "chimichanga",     allergens: ["wheat", "gluten", "dairy", "legumes"], source: "dish", note: "Deep-fried burrito in a flour tortilla" },
  { term: "wonton soup",     allergens: ["wheat", "gluten", "soy"],           source: "dish", note: "Wheat-wrapper dumplings in a soy-seasoned broth" },
  { term: "egg drop soup",   allergens: ["egg"],                              source: "dish", note: "Chinese soup with egg threads; often thickened with cornstarch" },
  { term: "miso soup",       allergens: ["soy"],                              source: "dish", note: "Miso paste is a fermented soy product" },
  { term: "grilled cheese",  allergens: ["dairy", "wheat", "gluten"],         source: "dish", note: "Melted cheese between buttered wheat bread slices" },
  { term: "mac and cheese",  allergens: ["dairy", "wheat", "gluten"],         source: "dish", note: "Macaroni (wheat pasta) in a cheese sauce" },
  { term: "macaroni and cheese", allergens: ["dairy", "wheat", "gluten"],     source: "dish" },
  { term: "reuben",          allergens: ["dairy", "wheat", "gluten"],         source: "dish", note: "Corned beef sandwich with Swiss cheese on rye bread" },
  { term: "rueben",          allergens: ["dairy", "wheat", "gluten"],         source: "dish", note: "Common spelling variant of Reuben sandwich" },
  { term: "club sandwich",   allergens: ["wheat", "gluten", "egg", "dairy"],  source: "dish", note: "Triple-decker on toasted bread with mayo" },
  { term: "loaded fries",    allergens: ["dairy"],                            source: "dish", note: "Fries topped with cheese sauce and/or sour cream" },
  { term: "cheese fries",    allergens: ["dairy"],                            source: "dish" },
  { term: "poutine",         allergens: ["dairy", "wheat", "gluten"],         source: "dish", note: "Fries + cheese curds + gravy (gravy may contain wheat)" },
  { term: "spinach dip",     allergens: ["dairy"],                            source: "dish", note: "Cream cheese or sour cream based dip" },
  { term: "artichoke dip",   allergens: ["dairy"],                            source: "dish", note: "Cream cheese or mayo based dip" },
  { term: "french onion soup", allergens: ["dairy", "wheat", "gluten"],       source: "dish", note: "Topped with croutons and melted cheese; broth often has flour" },
  { term: "chicken parmesan",allergens: ["dairy", "wheat", "gluten", "egg"],  source: "dish", note: "Breaded chicken (wheat+egg) baked with tomato sauce and mozzarella" },
  { term: "chicken parm",    allergens: ["dairy", "wheat", "gluten", "egg"],  source: "dish" },
  { term: "eggplant parm",   allergens: ["dairy", "wheat", "gluten", "egg"],  source: "dish", note: "Breaded eggplant with tomato sauce and mozzarella" },
];
