// lib/engine/allergenVocabulary.ts
// Weighted allergen vocabulary for direct + synonym detection.
// Each entry maps a term (exact substring match after normalization) to one
// or more allergens plus the signal source that produced it.

import type { AllergenId, SignalSource } from "./types";

export type VocabEntry = {
  term: string;
  allergens: AllergenId[];
  source: SignalSource;
  note?: string;
};

export const ALLERGEN_VOCABULARY: VocabEntry[] = [
  // ─── DAIRY ─────────────────────────────────────────────────────────────────
  { term: "milk",            allergens: ["dairy"],         source: "direct" },
  { term: "butter",          allergens: ["dairy"],         source: "direct" },
  { term: "cheese",          allergens: ["dairy"],         source: "direct" },
  { term: "cream",           allergens: ["dairy"],         source: "direct" },
  { term: "whey",            allergens: ["dairy"],         source: "direct" },
  { term: "casein",          allergens: ["dairy"],         source: "synonym", note: "Milk protein" },
  { term: "yogurt",          allergens: ["dairy"],         source: "direct" },
  { term: "yoghurt",         allergens: ["dairy"],         source: "direct" },
  { term: "ghee",            allergens: ["dairy"],         source: "direct", note: "Clarified butter" },
  { term: "lactose",         allergens: ["dairy"],         source: "synonym" },
  { term: "lactalbumin",     allergens: ["dairy"],         source: "synonym" },
  { term: "creme",           allergens: ["dairy"],         source: "direct" },
  { term: "beurre",          allergens: ["dairy"],         source: "synonym", note: "French: butter" },
  { term: "fromage",         allergens: ["dairy"],         source: "synonym", note: "French: cheese" },
  { term: "gratin",          allergens: ["dairy"],         source: "dish",    note: "Au gratin = cheese sauce" },
  { term: "bechamel",        allergens: ["dairy", "wheat"], source: "sauce",  note: "White sauce" },
  { term: "hollandaise",     allergens: ["dairy", "egg"],  source: "sauce",   note: "Butter + egg yolk sauce" },
  { term: "mornay",          allergens: ["dairy", "wheat"], source: "sauce",  note: "Béchamel + cheese" },
  { term: "alfredo",         allergens: ["dairy"],         source: "dish",    note: "Cream + parmesan sauce" },
  { term: "carbonara",       allergens: ["dairy", "egg"],  source: "dish",    note: "Cream/egg + cheese sauce" },
  { term: "ricotta",         allergens: ["dairy"],         source: "direct" },
  { term: "mozzarella",      allergens: ["dairy"],         source: "direct" },
  { term: "parmesan",        allergens: ["dairy"],         source: "direct" },
  { term: "cheddar",         allergens: ["dairy"],         source: "direct" },
  { term: "brie",            allergens: ["dairy"],         source: "direct" },
  { term: "feta",            allergens: ["dairy"],         source: "direct" },
  { term: "gouda",           allergens: ["dairy"],         source: "direct" },
  { term: "provolone",       allergens: ["dairy"],         source: "direct" },
  { term: "gorgonzola",      allergens: ["dairy"],         source: "direct" },
  { term: "blue cheese",     allergens: ["dairy"],         source: "direct" },
  { term: "ranch",           allergens: ["dairy", "egg"],  source: "sauce",   note: "Buttermilk + mayo base" },
  { term: "ice cream",       allergens: ["dairy"],         source: "direct" },
  { term: "gelato",          allergens: ["dairy"],         source: "direct" },
  { term: "sour cream",      allergens: ["dairy"],         source: "direct" },
  { term: "half and half",   allergens: ["dairy"],         source: "direct" },
  { term: "heavy cream",     allergens: ["dairy"],         source: "direct" },
  { term: "whipped cream",   allergens: ["dairy"],         source: "direct" },
  { term: "milk chocolate",  allergens: ["dairy"],         source: "direct" },
  { term: "latte",           allergens: ["dairy"],         source: "direct", note: "Espresso + steamed milk" },
  { term: "cappuccino",      allergens: ["dairy"],         source: "direct" },
  { term: "macchiato",       allergens: ["dairy"],         source: "direct" },
  { term: "flat white",      allergens: ["dairy"],         source: "direct" },

  // ─── EGG ───────────────────────────────────────────────────────────────────
  { term: "egg",             allergens: ["egg"],           source: "direct" },
  { term: "mayo",            allergens: ["egg"],           source: "direct" },
  { term: "mayonnaise",      allergens: ["egg"],           source: "direct" },
  { term: "aioli",           allergens: ["egg"],           source: "synonym", note: "Mayo-based" },
  { term: "meringue",        allergens: ["egg"],           source: "direct" },
  { term: "custard",         allergens: ["egg", "dairy"],  source: "direct" },
  { term: "frittata",        allergens: ["egg"],           source: "direct" },
  { term: "quiche",          allergens: ["egg", "dairy", "wheat"], source: "dish" },
  { term: "souffle",         allergens: ["egg", "dairy"],  source: "dish" },
  { term: "eggnog",          allergens: ["egg", "dairy"],  source: "direct" },
  { term: "lecithin",        allergens: ["egg", "soy"],    source: "synonym", note: "Often egg or soy derived" },
  { term: "albumen",         allergens: ["egg"],           source: "synonym", note: "Egg white" },
  { term: "ovalbumin",       allergens: ["egg"],           source: "synonym" },
  { term: "ovomucin",        allergens: ["egg"],           source: "synonym" },
  { term: "livetin",         allergens: ["egg"],           source: "synonym" },
  { term: "globulin",        allergens: ["egg"],           source: "synonym" },
  { term: "egg wash",        allergens: ["egg"],           source: "prep",    note: "Brushed on baked goods/breaded items" },
  { term: "deviled",         allergens: ["egg"],           source: "dish",    note: "Deviled eggs" },
  { term: "benedict",        allergens: ["egg", "dairy"],  source: "dish",    note: "Eggs Benedict = poached egg + hollandaise" },
  { term: "brioche",         allergens: ["wheat", "gluten", "egg", "dairy"], source: "dish" },
  { term: "croissant",       allergens: ["wheat", "gluten", "dairy", "egg"], source: "dish" },
  { term: "waffle",          allergens: ["wheat", "gluten", "egg", "dairy"], source: "dish" },
  { term: "pancake",         allergens: ["wheat", "gluten", "egg", "dairy"], source: "dish" },
  { term: "french toast",    allergens: ["wheat", "gluten", "egg", "dairy"], source: "dish" },

  // ─── SOY ───────────────────────────────────────────────────────────────────
  { term: "soy sauce",       allergens: ["soy", "wheat", "gluten"], source: "direct" },
  { term: "soy",             allergens: ["soy"],           source: "direct" },
  { term: "tofu",            allergens: ["soy"],           source: "direct" },
  { term: "miso",            allergens: ["soy"],           source: "direct" },
  { term: "edamame",         allergens: ["soy"],           source: "direct" },
  { term: "tempeh",          allergens: ["soy"],           source: "direct" },
  { term: "tamari",          allergens: ["soy"],           source: "direct" },
  { term: "natto",           allergens: ["soy"],           source: "direct" },
  { term: "shoyu",           allergens: ["soy", "wheat", "gluten"], source: "synonym", note: "Japanese soy sauce" },
  { term: "ponzu",           allergens: ["soy", "fish"],   source: "sauce",   note: "Soy + citrus + dashi" },
  { term: "hoisin",          allergens: ["soy", "wheat", "gluten"], source: "sauce" },
  { term: "teriyaki",        allergens: ["soy", "wheat", "gluten"], source: "sauce" },
  { term: "yakitori",        allergens: ["soy", "wheat", "gluten"], source: "dish", note: "Teriyaki-glazed chicken" },
  { term: "gyoza",           allergens: ["wheat", "gluten", "soy"], source: "dish" },
  { term: "dumpling",        allergens: ["wheat", "gluten", "soy"], source: "dish" },
  { term: "edamame",         allergens: ["soy"],           source: "direct" },

  // ─── WHEAT / GLUTEN ────────────────────────────────────────────────────────
  { term: "flour",           allergens: ["wheat", "gluten"], source: "direct" },
  { term: "bread",           allergens: ["wheat", "gluten"], source: "direct" },
  { term: "bun",             allergens: ["wheat", "gluten"], source: "direct" },
  { term: "gluten",          allergens: ["gluten", "wheat"], source: "direct" },
  { term: "barley",          allergens: ["gluten"],         source: "direct" },
  { term: "rye",             allergens: ["gluten"],         source: "direct" },
  { term: "pasta",           allergens: ["wheat", "gluten"], source: "direct" },
  { term: "noodle",          allergens: ["wheat", "gluten"], source: "direct" },
  { term: "crouton",         allergens: ["wheat", "gluten"], source: "direct" },
  { term: "tortilla",        allergens: ["wheat", "gluten"], source: "direct", note: "Flour tortillas; corn tortillas are safe" },
  { term: "pretzel",         allergens: ["wheat", "gluten"], source: "direct" },
  { term: "pita",            allergens: ["wheat", "gluten"], source: "direct" },
  { term: "wrap",            allergens: ["wheat", "gluten"], source: "direct" },
  { term: "sandwich",        allergens: ["wheat", "gluten"], source: "direct" },
  { term: "sub",             allergens: ["wheat", "gluten"], source: "direct" },
  { term: "roll",            allergens: ["wheat", "gluten"], source: "direct" },
  { term: "crust",           allergens: ["wheat", "gluten"], source: "direct" },
  { term: "breaded",         allergens: ["wheat", "gluten"], source: "prep" },
  { term: "battered",        allergens: ["wheat", "gluten", "egg"], source: "prep" },
  { term: "tempura",         allergens: ["wheat", "gluten", "egg"], source: "dish" },
  { term: "panko",           allergens: ["wheat", "gluten"], source: "direct", note: "Japanese breadcrumbs" },
  { term: "breadcrumb",      allergens: ["wheat", "gluten"], source: "direct" },
  { term: "semolina",        allergens: ["wheat", "gluten"], source: "direct" },
  { term: "spelt",           allergens: ["wheat", "gluten"], source: "direct" },
  { term: "kamut",           allergens: ["wheat", "gluten"], source: "direct" },
  { term: "farro",           allergens: ["wheat", "gluten"], source: "direct" },
  { term: "bulgur",          allergens: ["wheat", "gluten"], source: "direct" },
  { term: "couscous",        allergens: ["wheat", "gluten"], source: "direct" },
  { term: "seitan",          allergens: ["wheat", "gluten"], source: "direct", note: "Pure wheat gluten" },
  { term: "pizza",           allergens: ["wheat", "gluten", "dairy"], source: "dish" },
  { term: "calzone",         allergens: ["wheat", "gluten", "dairy"], source: "dish" },
  { term: "stromboli",       allergens: ["wheat", "gluten", "dairy"], source: "dish" },
  { term: "ramen",           allergens: ["wheat", "gluten", "soy"],   source: "dish" },
  { term: "udon",            allergens: ["wheat", "gluten"],          source: "dish" },
  { term: "lo mein",         allergens: ["wheat", "gluten", "soy"],   source: "dish" },
  { term: "chow mein",       allergens: ["wheat", "gluten", "soy"],   source: "dish" },
  { term: "malt",            allergens: ["gluten"],         source: "direct", note: "Barley malt" },
  { term: "malt vinegar",    allergens: ["gluten"],         source: "direct" },

  // ─── FISH ──────────────────────────────────────────────────────────────────
  { term: "fish sauce",      allergens: ["fish"],           source: "direct" },
  { term: "worcestershire",  allergens: ["fish"],           source: "synonym", note: "Typically contains anchovies" },
  { term: "anchovy",         allergens: ["fish"],           source: "direct" },
  { term: "anchovies",       allergens: ["fish"],           source: "direct" },
  { term: "salmon",          allergens: ["fish"],           source: "direct" },
  { term: "tuna",            allergens: ["fish"],           source: "direct" },
  { term: "cod",             allergens: ["fish"],           source: "direct" },
  { term: "tilapia",         allergens: ["fish"],           source: "direct" },
  { term: "halibut",         allergens: ["fish"],           source: "direct" },
  { term: "mahi",            allergens: ["fish"],           source: "direct" },
  { term: "mahi mahi",       allergens: ["fish"],           source: "direct" },
  { term: "snapper",         allergens: ["fish"],           source: "direct" },
  { term: "bass",            allergens: ["fish"],           source: "direct" },
  { term: "flounder",        allergens: ["fish"],           source: "direct" },
  { term: "sole",            allergens: ["fish"],           source: "direct" },
  { term: "catfish",         allergens: ["fish"],           source: "direct" },
  { term: "trout",           allergens: ["fish"],           source: "direct" },
  { term: "herring",         allergens: ["fish"],           source: "direct" },
  { term: "sardine",         allergens: ["fish"],           source: "direct" },
  { term: "mackerel",        allergens: ["fish"],           source: "direct" },
  { term: "swordfish",       allergens: ["fish"],           source: "direct" },
  { term: "dashi",           allergens: ["fish"],           source: "synonym", note: "Japanese stock made from bonito/kelp" },
  { term: "bonito",          allergens: ["fish"],           source: "direct" },
  { term: "katsuobushi",     allergens: ["fish"],           source: "direct", note: "Dried bonito flakes" },
  { term: "caesar",          allergens: ["fish", "egg", "dairy"], source: "dish", note: "Traditional Caesar = anchovy + egg + parmesan" },
  { term: "nicoise",         allergens: ["fish"],           source: "dish",   note: "Salade niçoise contains tuna/anchovies" },

  // ─── SHELLFISH ─────────────────────────────────────────────────────────────
  { term: "shrimp",          allergens: ["shellfish"],      source: "direct" },
  { term: "crab",            allergens: ["shellfish"],      source: "direct" },
  { term: "lobster",         allergens: ["shellfish"],      source: "direct" },
  { term: "clam",            allergens: ["shellfish"],      source: "direct" },
  { term: "oyster",          allergens: ["shellfish"],      source: "direct" },
  { term: "scallop",         allergens: ["shellfish"],      source: "direct" },
  { term: "mussel",          allergens: ["shellfish"],      source: "direct" },
  { term: "calamari",        allergens: ["shellfish"],      source: "direct" },
  { term: "squid",           allergens: ["shellfish"],      source: "direct" },
  { term: "octopus",         allergens: ["shellfish"],      source: "direct" },
  { term: "prawn",           allergens: ["shellfish"],      source: "direct" },
  { term: "langoustine",     allergens: ["shellfish"],      source: "direct" },
  { term: "crayfish",        allergens: ["shellfish"],      source: "direct" },
  { term: "seafood",         allergens: ["shellfish", "fish"], source: "direct" },
  { term: "surf and turf",   allergens: ["shellfish"],      source: "dish" },
  { term: "cioppino",        allergens: ["shellfish", "fish"], source: "dish" },
  { term: "bouillabaisse",   allergens: ["shellfish", "fish"], source: "dish" },
  { term: "paella",          allergens: ["shellfish", "fish"], source: "dish" },
  { term: "bisque",          allergens: ["shellfish", "dairy"], source: "dish", note: "Often lobster/shrimp bisque with cream" },

  // ─── PEANUT ────────────────────────────────────────────────────────────────
  { term: "peanut butter",   allergens: ["peanut"],         source: "direct" },
  { term: "peanut",          allergens: ["peanut"],         source: "direct" },
  { term: "satay",           allergens: ["peanut"],         source: "dish",   note: "Satay sauce = peanut-based" },
  { term: "pad thai",        allergens: ["peanut", "shellfish", "egg"], source: "dish" },
  { term: "gado gado",       allergens: ["peanut"],         source: "dish" },
  { term: "kung pao",        allergens: ["peanut"],         source: "dish" },
  { term: "groundnut",       allergens: ["peanut"],         source: "synonym" },
  { term: "monkey nuts",     allergens: ["peanut"],         source: "synonym" },
  { term: "peanut oil",      allergens: ["peanut"],         source: "direct" },
  { term: "arachis oil",     allergens: ["peanut"],         source: "synonym", note: "Peanut oil (scientific name)" },

  // ─── TREE NUT ──────────────────────────────────────────────────────────────
  { term: "pine nut",        allergens: ["tree-nut"],       source: "direct" },
  { term: "almond",          allergens: ["tree-nut"],       source: "direct" },
  { term: "walnut",          allergens: ["tree-nut"],       source: "direct" },
  { term: "cashew",          allergens: ["tree-nut"],       source: "direct" },
  { term: "pecan",           allergens: ["tree-nut"],       source: "direct" },
  { term: "pistachio",       allergens: ["tree-nut"],       source: "direct" },
  { term: "hazelnut",        allergens: ["tree-nut"],       source: "direct" },
  { term: "macadamia",       allergens: ["tree-nut"],       source: "direct" },
  { term: "chestnut",        allergens: ["tree-nut"],       source: "direct" },
  { term: "brazil nut",      allergens: ["tree-nut"],       source: "direct" },
  { term: "coconut",         allergens: ["tree-nut"],       source: "direct", note: "FDA classifies as tree nut" },
  { term: "pesto",           allergens: ["tree-nut", "dairy"], source: "sauce", note: "Pine nuts + parmesan" },
  { term: "praline",         allergens: ["tree-nut"],       source: "direct" },
  { term: "marzipan",        allergens: ["tree-nut"],       source: "direct", note: "Almond paste" },
  { term: "frangipane",      allergens: ["tree-nut", "egg", "dairy"], source: "dish" },
  { term: "gianduja",        allergens: ["tree-nut", "dairy"], source: "direct", note: "Chocolate + hazelnut" },
  { term: "nutella",         allergens: ["tree-nut", "dairy"], source: "direct" },
  { term: "nut",             allergens: ["tree-nut"],       source: "direct", note: "Generic nut mention" },
  { term: "nut butter",      allergens: ["tree-nut"],       source: "direct" },
  { term: "trail mix",       allergens: ["tree-nut", "peanut"], source: "dish" },
  { term: "granola",         allergens: ["oats", "tree-nut"], source: "dish" },

  // ─── SESAME ────────────────────────────────────────────────────────────────
  { term: "sesame",          allergens: ["sesame"],         source: "direct" },
  { term: "tahini",          allergens: ["sesame"],         source: "direct" },
  { term: "hummus",          allergens: ["sesame", "legumes"], source: "dish", note: "Chickpeas + tahini" },
  { term: "sesame oil",      allergens: ["sesame"],         source: "direct" },
  { term: "sesame seed",     allergens: ["sesame"],         source: "direct" },
  { term: "bagel",           allergens: ["sesame", "wheat", "gluten"], source: "dish", note: "Often has sesame seeds" },
  { term: "gochujang",       allergens: ["sesame", "wheat", "gluten"], source: "sauce" },
  { term: "za atar",         allergens: ["sesame"],         source: "dish",   note: "Spice mix with sesame" },
  { term: "zatar",           allergens: ["sesame"],         source: "dish" },
  { term: "benne",           allergens: ["sesame"],         source: "synonym", note: "African/Southern term for sesame" },

  // ─── CORN ──────────────────────────────────────────────────────────────────
  { term: "cornstarch",      allergens: ["corn"],           source: "direct" },
  { term: "corn",            allergens: ["corn"],           source: "direct" },
  { term: "masa",            allergens: ["corn"],           source: "direct" },
  { term: "polenta",         allergens: ["corn"],           source: "direct" },
  { term: "grits",           allergens: ["corn"],           source: "direct" },
  { term: "hominy",          allergens: ["corn"],           source: "direct" },
  { term: "corn tortilla",   allergens: ["corn"],           source: "direct" },
  { term: "corn chip",       allergens: ["corn"],           source: "direct" },
  { term: "corn syrup",      allergens: ["corn"],           source: "direct" },
  { term: "popcorn",         allergens: ["corn"],           source: "direct" },

  // ─── MUSTARD ───────────────────────────────────────────────────────────────
  { term: "mustard",         allergens: ["mustard"],        source: "direct" },
  { term: "dijon",           allergens: ["mustard"],        source: "direct" },
  { term: "whole grain mustard", allergens: ["mustard"],    source: "direct" },
  { term: "hot dog mustard", allergens: ["mustard"],        source: "direct" },

  // ─── LEGUMES ───────────────────────────────────────────────────────────────
  { term: "lupin",           allergens: ["legumes"],        source: "direct" },
  { term: "lupine",          allergens: ["legumes"],        source: "direct" },
  { term: "fava bean",       allergens: ["legumes"],        source: "direct" },
  { term: "broad bean",      allergens: ["legumes"],        source: "direct" },
  { term: "kidney bean",     allergens: ["legumes"],        source: "direct" },
  { term: "pinto bean",      allergens: ["legumes"],        source: "direct" },
  { term: "black bean",      allergens: ["legumes"],        source: "direct" },
  { term: "chickpea",        allergens: ["legumes"],        source: "direct" },
  { term: "chickpeas",       allergens: ["legumes"],        source: "direct" },
  { term: "lentil",          allergens: ["legumes"],        source: "direct" },
  { term: "lentils",         allergens: ["legumes"],        source: "direct" },
  { term: "dal",             allergens: ["legumes"],        source: "direct", note: "Indian lentil dish" },
  { term: "dhal",            allergens: ["legumes"],        source: "direct" },
  { term: "refried beans",   allergens: ["legumes"],        source: "direct" },
  { term: "bean",            allergens: ["legumes"],        source: "direct" },
  { term: "beans",           allergens: ["legumes"],        source: "direct" },
  { term: "pea",             allergens: ["legumes"],        source: "direct", note: "Peas are legumes" },
  { term: "peas",            allergens: ["legumes"],        source: "direct" },

  // ─── OATS ──────────────────────────────────────────────────────────────────
  { term: "oat",             allergens: ["oats"],           source: "direct" },
  { term: "oats",            allergens: ["oats"],           source: "direct" },
  { term: "oatmeal",         allergens: ["oats"],           source: "direct" },
  { term: "muesli",          allergens: ["oats"],           source: "direct" },
];
