// lib/engine/riskScorer.ts
// Aggregates all risk signals for one item into a final risk level + confidence.
//
// Conservative principle: when in doubt, escalate.
// Signal weight thresholds:
//   weight >= 3 → direct/synonym/dish = AVOID (these are near-certain allergen presence)
//   weight 1-2  → prep/cuisine/ambiguity = ASK (possible but not certain)
//   no signals  → SAFE

import type { AllergenId, RiskLevel, ConfidenceLevel, RiskSignal } from "./types";
import type { SourceType } from "@/lib/types";

type ScoreResult = {
  risk: RiskLevel;
  confidence: ConfidenceLevel;
  matchedAllergens: AllergenId[];
  explanation: string;
};

/** Map source data quality to confidence */
function sourceToConfidence(sourceType?: SourceType): ConfidenceLevel {
  switch (sourceType) {
    case "official":
    case "verified-dataset":
      return "high";
    case "aggregator":
      return "medium";
    case "scraped":
    case "user-input":
    default:
      return "low";
  }
}

/** Produce a concise human-readable explanation */
function buildExplanation(
  risk: RiskLevel,
  signals: RiskSignal[],
  matchedAllergens: AllergenId[]
): string {
  if (risk === "avoid") {
    const reasons = signals
      .filter((s) => matchedAllergens.includes(s.allergen) && s.weight >= 3)
      .slice(0, 2)
      .map((s) => s.reason);
    return reasons.length
      ? reasons.join(". ")
      : `Contains ${matchedAllergens.join(", ")} — avoid.`;
  }

  if (risk === "ask") {
    const reasons = signals
      .filter((s) => matchedAllergens.includes(s.allergen))
      .slice(0, 2)
      .map((s) => s.reason);
    return reasons.length
      ? reasons.join(". ") + " — confirm with staff."
      : "Possible allergen presence — confirm with staff.";
  }

  return "No allergens detected for your profile. Always mention your allergy when ordering.";
}

/**
 * Score a single menu item.
 *
 * @param signals        All signals generated by all detection layers
 * @param userAllergens  The user's allergen profile
 * @param sourceType     Data source (affects confidence, not risk)
 */
export function scoreItem(
  signals: RiskSignal[],
  userAllergens: AllergenId[],
  sourceType?: SourceType
): ScoreResult {
  // Only consider signals for allergens in the user's profile
  const relevant = signals.filter((s) => userAllergens.includes(s.allergen));

  if (relevant.length === 0) {
    return {
      risk:             "safe",
      confidence:       sourceToConfidence(sourceType),
      matchedAllergens: [],
      explanation:      "No allergens detected for your profile. Always mention your allergy when ordering.",
    };
  }

  // High-confidence signals (weight >= 3): direct/synonym/dish/sauce → AVOID
  const highWeightHits = relevant.filter((s) => s.weight >= 3);
  if (highWeightHits.length > 0) {
    const allergens = [...new Set(highWeightHits.map((s) => s.allergen))];
    return {
      risk:             "avoid",
      confidence:       sourceToConfidence(sourceType),
      matchedAllergens: allergens,
      explanation:      buildExplanation("avoid", relevant, allergens),
    };
  }

  // Low-weight signals (weight 1-2): prep/cuisine/ambiguity → ASK
  const allergens = [...new Set(relevant.map((s) => s.allergen))];
  return {
    risk:             "ask",
    confidence:       sourceToConfidence(sourceType),
    matchedAllergens: allergens,
    explanation:      buildExplanation("ask", relevant, allergens),
  };
}
