"use client";

import { useState, Fragment } from "react";
import type { BuilderStep } from "@/lib/types";
import type { AnalyzedMenuSection, AnalyzedMenuItem } from "@/lib/analysis";
import { useTheme } from "@/lib/themeContext";
import { RISK_COLOR } from "@/lib/riskColors";

type Props = {
  steps: BuilderStep[];
  sections: AnalyzedMenuSection[];
  orderedItemIds: Set<string>;
  onToggleOrder: (id: string) => void;
  onOpenOrder: () => void;
  onBrowse: () => void;
  restaurantName?: string;
};

export function GuidedOrderBuilder({
  steps, sections, orderedItemIds, onToggleOrder, onOpenOrder, onBrowse, restaurantName,
}: Props) {
  const { isDark } = useTheme();
  const [copied, setCopied] = useState(false);
  const [mealTime, setMealTime] = useState<"lunch" | "breakfast">("lunch");

  const hasMealTimeSteps = steps.some((s) => s.mealTime);
  const activeSteps = hasMealTimeSteps
    ? steps.filter((s) => !s.mealTime || s.mealTime === mealTime)
    : steps;

  function getStepSections(s: BuilderStep): { name: string; items: AnalyzedMenuItem[] }[] {
    if (s.categories) {
      return sections
        .filter((sec) => s.categories!.includes(sec.sectionName))
        .map((sec) => ({ name: sec.sectionName, items: sec.items }))
        .filter((g) => g.items.length > 0);
    }
    const sec = sections.find((sec) => sec.sectionName === s.category);
    return sec ? [{ name: sec.sectionName, items: sec.items }] : [];
  }

  // Build menu board structure with global sequential numbers.
  // Items stay in their original data order (matching the real drive-thru board).
  // Risk is communicated via number color, not position.
  let globalNum = 1;
  const menuBoard = activeSteps.map((step) => {
    const subs = getStepSections(step);
    return {
      step,
      subsections: subs.map(({ name, items }) => ({
        name,
        numbered: items.map((item) => ({ item, num: globalNum++ })),
      })),
    };
  });

  const totalOrdered = orderedItemIds.size;

  function selectItem(step: BuilderStep, allStepItems: AnalyzedMenuItem[], item: AnalyzedMenuItem) {
    if (item.risk === "avoid") return;
    if (step.maxSelect === 1) {
      for (const si of allStepItems) {
        if (si.id !== item.id && orderedItemIds.has(si.id)) onToggleOrder(si.id);
      }
      if (!orderedItemIds.has(item.id)) onToggleOrder(item.id);
    } else {
      onToggleOrder(item.id);
    }
  }

  function copyOrder() {
    const lines: string[] = [];
    if (restaurantName) lines.push(`My order at ${restaurantName}`);
    lines.push("─".repeat(28));
    for (const { step, subsections } of menuBoard) {
      const picked = subsections.flatMap((s) => s.numbered.map((n) => n.item)).filter((i) => orderedItemIds.has(i.id));
      if (!picked.length) continue;
      lines.push(`${step.label}: ${picked.map((i) => i.name).join(", ")}`);
    }
    lines.push("─".repeat(28));
    lines.push("Generated by AllergEats");
    navigator.clipboard.writeText(lines.join("\n")).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }).catch(() => {});
  }

  const card: React.CSSProperties = {
    background: isDark ? "rgba(255,255,255,0.04)" : "rgba(255,255,255,0.82)",
    WebkitBackdropFilter: "blur(20px)", backdropFilter: "blur(20px)",
    border: `1px solid ${isDark ? "rgba(255,255,255,0.09)" : "rgba(0,0,0,0.07)"}`,
    borderRadius: 16,
    overflow: "hidden",
    boxShadow: isDark
      ? "0 4px 24px rgba(0,0,0,0.3), inset 0 1px 0 rgba(255,255,255,0.05)"
      : "0 4px 24px rgba(0,0,0,0.06), inset 0 1px 0 rgba(255,255,255,0.9)",
  };

  const divider = isDark ? "rgba(255,255,255,0.07)" : "rgba(0,0,0,0.06)";

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 20 }}>

      {/* ── Meal time toggle ── */}
      {hasMealTimeSteps && (
        <div style={{
          display: "flex", gap: 6, padding: "3px",
          background: isDark ? "rgba(255,255,255,0.06)" : "rgba(0,0,0,0.05)",
          borderRadius: 14,
          alignSelf: "flex-start",
        }}>
          {(["lunch", "breakfast"] as const).map((t) => {
            const active = mealTime === t;
            return (
              <button
                key={t}
                type="button"
                onClick={() => setMealTime(t)}
                style={{
                  padding: "7px 18px", borderRadius: 11, border: "none", cursor: "pointer",
                  fontSize: 13, fontWeight: 700,
                  background: active ? "var(--c-brand)" : "transparent",
                  color: active ? "var(--c-brand-fg)" : "var(--c-sub)",
                  transition: "background 0.15s, color 0.15s",
                  letterSpacing: "-0.01em",
                  boxShadow: active ? "0 1px 6px rgba(0,0,0,0.18)" : "none",
                }}
              >
                {t === "lunch" ? "Lunch & Dinner" : "Breakfast"}
              </button>
            );
          })}
        </div>
      )}

      {menuBoard.map(({ step, subsections }) => {
        const isSingle = step.maxSelect === 1;
        const allStepItems = subsections.flatMap((s) => s.numbered.map((n) => n.item));
        const picked = allStepItems.filter((i) => orderedItemIds.has(i.id));
        const allAvoid = allStepItems.length > 0 && allStepItems.every((i) => i.risk === "avoid");

        return (
          <div key={step.label}>

            {/* ── Section header ── */}
            <div style={{
              display: "flex", alignItems: "baseline", justifyContent: "space-between",
              padding: "0 2px 8px",
            }}>
              <div style={{
                fontSize: 13, fontWeight: 900, textTransform: "uppercase",
                letterSpacing: "0.09em", color: "var(--c-brand)",
                display: "flex", alignItems: "center", gap: 7,
              }}>
                {step.label}
                {picked.length > 0 && (
                  <span style={{
                    width: 7, height: 7, borderRadius: "50%",
                    background: "#16a34a", display: "inline-block", flexShrink: 0,
                  }} />
                )}
              </div>
              <span style={{
                fontSize: 10, fontWeight: 700, textTransform: "uppercase",
                letterSpacing: "0.06em", color: "var(--c-sub)",
              }}>
                {isSingle
                  ? "Choose 1"
                  : step.maxSelect < 99
                    ? `Choose up to ${step.maxSelect}`
                    : "Choose any"}
                {!step.required && " · Optional"}
              </span>
            </div>

            {/* ── Items card ── */}
            {allAvoid ? (
              <div style={{
                ...card,
                padding: "14px 18px",
                display: "flex", alignItems: "center", gap: 10,
                background: isDark ? "rgba(220,38,38,0.07)" : "rgba(220,38,38,0.04)",
                border: `1px solid rgba(220,38,38,${isDark ? "0.25" : "0.15"})`,
              }}>
                <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="#dc2626" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
                  <path d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z"/>
                  <line x1="12" y1="9" x2="12" y2="13"/><line x1="12" y1="17" x2="12.01" y2="17"/>
                </svg>
                <span style={{ fontSize: 13, fontWeight: 700, color: "#dc2626" }}>All items contain your allergens</span>
              </div>
            ) : (
              <div style={card}>
                {subsections.map(({ name: subName, numbered }, subIdx) => {
                  const isLastSub = subIdx === subsections.length - 1;
                  return (
                    <Fragment key={subIdx}>
                      {/* Sub-header when step spans multiple sections */}
                      {subsections.length > 1 && (
                        <div style={{
                          padding: "8px 18px 7px",
                          fontSize: 10, fontWeight: 800, textTransform: "uppercase",
                          letterSpacing: "0.08em", color: "var(--c-sub)",
                          background: isDark ? "rgba(255,255,255,0.03)" : "rgba(0,0,0,0.025)",
                          borderBottom: `1px solid ${divider}`,
                        }}>
                          {subName}
                        </div>
                      )}

                      {numbered.map(({ item, num }, idx) => {
                        const isSelected = orderedItemIds.has(item.id);
                        const isAvoid = item.risk === "avoid";
                        const riskColor = RISK_COLOR[item.risk] ?? "#9ca3af";
                        const isLast = isLastSub && idx === numbered.length - 1;

                        return (
                          <button
                            key={item.id}
                            type="button"
                            onClick={() => selectItem(step, allStepItems, item)}
                            disabled={isAvoid}
                            style={{
                              display: "flex", alignItems: "stretch",
                              width: "100%", textAlign: "left", padding: 0,
                              background: isSelected
                                ? isDark ? "rgba(31,189,204,0.09)" : "rgba(0,150,165,0.06)"
                                : "transparent",
                              border: "none",
                              borderBottom: isLast ? "none" : `1px solid ${divider}`,
                              cursor: isAvoid ? "not-allowed" : "pointer",
                              opacity: isAvoid ? 0.35 : 1,
                              transition: "background 0.15s",
                              minHeight: 62,
                              WebkitTapHighlightColor: "transparent",
                            }}
                          >
                            {/* Number column */}
                            <div style={{
                              width: 54, flexShrink: 0,
                              display: "flex", alignItems: "center", justifyContent: "center",
                              borderRight: `1px solid ${divider}`,
                              background: isDark ? "rgba(0,0,0,0.18)" : "rgba(0,0,0,0.03)",
                            }}>
                              <span style={{
                                fontSize: 22, fontWeight: 900, lineHeight: 1,
                                fontVariantNumeric: "tabular-nums",
                                letterSpacing: "-0.03em",
                                color: isAvoid ? "#9ca3af" : riskColor,
                                textShadow: (!isAvoid && isDark) ? `0 0 14px ${riskColor}66` : "none",
                              }}>
                                {num}
                              </span>
                            </div>

                            {/* Name + allergen warning */}
                            <div style={{ display: "flex", alignItems: "center", gap: 10, flex: 1, padding: "14px 14px 14px 16px" }}>
                              <div style={{ flex: 1, minWidth: 0 }}>
                                <div style={{
                                  fontSize: 16, fontWeight: 800,
                                  color: isAvoid ? "var(--c-sub)" : "var(--c-text)",
                                  lineHeight: 1.25, letterSpacing: "-0.02em",
                                  textDecoration: isAvoid ? "line-through" : "none",
                                }}>
                                  {item.name}
                                </div>
                                {item.userAllergenHits.length > 0 && (
                                  <div style={{
                                    display: "inline-flex", alignItems: "center", gap: 4,
                                    fontSize: 11, color: "#dc2626", fontWeight: 700, marginTop: 5,
                                    background: "rgba(220,38,38,0.08)", borderRadius: 6, padding: "2px 7px",
                                  }}>
                                    <svg width="9" height="9" viewBox="0 0 24 24" fill="none" stroke="#dc2626" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
                                      <path d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z"/>
                                    </svg>
                                    {item.userAllergenHits.map((a) => a.replace(/-/g, " ")).join(", ")}
                                  </div>
                                )}
                              </div>

                              {!isAvoid && (
                                <div style={{
                                  width: 24, height: 24,
                                  borderRadius: isSingle ? 999 : 7,
                                  flexShrink: 0,
                                  border: isSelected ? "none" : `2px solid ${isDark ? "rgba(255,255,255,0.2)" : "rgba(0,0,0,0.16)"}`,
                                  background: isSelected ? "var(--c-brand)" : "transparent",
                                  display: "flex", alignItems: "center", justifyContent: "center",
                                  transition: "all 0.15s",
                                  boxShadow: isSelected ? "0 2px 8px rgba(31,189,204,0.4)" : "none",
                                }}>
                                  {isSelected && (
                                    <svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth="3.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
                                      <polyline points="20 6 9 17 4 12"/>
                                    </svg>
                                  )}
                                </div>
                              )}
                            </div>
                          </button>
                        );
                      })}
                    </Fragment>
                  );
                })}
              </div>
            )}
          </div>
        );
      })}

      {/* ── Order actions ── */}
      <div style={{ display: "flex", flexDirection: "column", gap: 10, paddingTop: 4 }}>
        {totalOrdered > 0 && (
          <button onClick={onOpenOrder} style={{
            width: "100%", padding: "15px 0", borderRadius: 16, border: "none",
            background: "var(--c-brand)", color: "var(--c-brand-fg)",
            fontSize: 16, fontWeight: 800, cursor: "pointer", minHeight: 54,
            letterSpacing: "-0.01em",
          }}>
            View order ({totalOrdered}) →
          </button>
        )}
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
          {totalOrdered > 0 ? (
            <button onClick={copyOrder} style={{
              background: "none", border: "none", fontSize: 13,
              color: copied ? "#16a34a" : "var(--c-sub)",
              cursor: "pointer", padding: "8px 0", fontWeight: 600,
            }}>
              {copied ? "✓ Copied!" : "Copy order"}
            </button>
          ) : <div />}
          <button onClick={onBrowse} style={{
            background: "none", border: "none", fontSize: 13, color: "var(--c-sub)",
            cursor: "pointer", padding: "8px 0", fontWeight: 600,
          }}>
            Browse full menu →
          </button>
        </div>
      </div>
    </div>
  );
}
