/**
 * Official allergen page URLs for each restaurant chain.
 * Used in the admin audit tool to link directly to the source.
 * Key = restaurant id from mockRestaurants.ts
 */
export const ALLERGEN_SOURCE_URLS: Record<string, string> = {
  "mcdonalds":       "https://www.mcdonalds.com/us/en-us/about-our-food/nutrition-calculator.html",
  "chipotle":        "https://www.chipotle.com/allergen-info",
  "chickfila":       "https://www.chick-fil-a.com/menu-items",
  "starbucks":       "https://www.starbucks.com/menu",
  "shakeshack":      "https://shakeshack.com/allergen-guide",
  "subway":          "https://www.subway.com/en-US/MenuNutrition/Nutrition/AllergenInformation",
  "tacobell":        "https://www.tacobell.com/nutrition/allergens",
  "burgerking":      "https://www.bk.com/nutrition/allergens",
  "wendys":          "https://www.wendys.com/nutrition-allergies",
  "panera":          "https://www.panerabread.com/en-us/articles/allergen-menu.html",
  "dunkin":          "https://www.dunkindonuts.com/en/menu/nutrition-allergens",
  "innout":          "https://www.in-n-out.com/menu/nutritional-information",
  "fiveguys":        "https://www.fiveguys.com/menu/nutrition-and-allergens",
  "popeyes":         "https://www.popeyes.com/nutrition",
  "kfc":             "https://www.kfc.com/nutrition/pdf/kfc_nutrition.pdf",
  "dominos":         "https://www.dominos.com/en/nutritional-information/",
  "jerseymikes":     "https://www.jerseymikes.com/nutrition/allergen-guide",
  "jimmyjohns":      "https://www.jimmyjohns.com/about/nutrition/allergens/",
  "chilis":          "https://www.chilis.com/info/allergen-info",
  "applebees":       "https://www.applebees.com/en/allergen-info",
  "texasroadhouse":  "https://www.texasroadhouse.com/nutrition-information",
  "longhorn":        "https://www.longhornsteakhouse.com/menu-allergen-info",
  "kjsteakhouse":    "",
  "ruthschris":      "https://www.ruthschris.com/wp-content/uploads/2024/01/Allergen-Menu.pdf",
  "coopershawk":     "https://www.coopershawkwinery.com/nutrition-info",
  "olivegarden":     "https://www.olivegarden.com/menu-allergen-info",
  "redlobster":      "https://www.redlobster.com/allergen-info",
  "ihop":            "https://www.ihop.com/en/more-info/allergen-menu-pdf",
  "dennys":          "https://www.dennys.com/allergen-info",
  "cheesecakefactory": "https://www.thecheesecakefactory.com/menu-allergen-info",
  "buffalowildwings": "https://www.buffalowildwings.com/en/info/menu-nutrition/",
  "wingstop":        "https://www.wingstop.com/nutrition",
  "pandaexpress":    "https://www.pandaexpress.com/allergen-info",
  "pfchangs":        "https://www.pfchangs.com/menus/allergen-menu.html",
  "raisingcanes":    "https://www.raisingcanes.com/allergen-info",
  "sonic":           "https://www.sonicdrivein.com/nutrition",
  "arbys":           "https://arbys.com/nutrition/allergens",
  "whataburger":     "https://www.whataburger.com/food/nutrition",
  "dairyqueen":      "https://www.dairyqueen.com/en-us/menu/nutrition/",
  "pizzahut":        "https://www.pizzahut.com/nutrition",
  "papajohns":       "https://www.papajohns.com/allergy-information.html",
  "qdoba":           "https://www.qdoba.com/allergen-info",
  "tgifridays":      "https://www.tgifridays.com/menu-allergendisclosure",
  "redrobin":        "https://www.redrobin.com/info/allergen-and-nutrition-information.html",
  "crackerbarrel":   "https://www.crackerbarrel.com/menu-pdfs/Allergen-Guide.pdf",
  "jackinthebox":    "https://www.jackinthebox.com/food/nutrition",
  "culvers":         "https://www.culvers.com/menu-and-nutrition/menu",
  "noodles":         "https://www.noodles.com/menu-info/allergens",
  "yardhouse":       "https://www.yardhouse.com/menu-info/allergens",
  "outback":         "https://www.outback.com/menu-info/allergens",
  "sweetgreen":      "https://www.sweetgreen.com/menu",
  "capitalgrille":   "https://www.thecapitalgrille.com/menu-info/allergens",
  "steaknshake":     "https://www.steaknshake.com/nutrition",
  "bojangles":       "https://www.bojangles.com/nutrition/",
  "carlsjr":         "https://www.carlsjr.com/menu/nutritional-calculator",
  "modpizza":        "https://modpizza.com/nutrition/",
  "smashburger":     "https://smashburger.com/allergens/",
  "zaxbys":          "https://www.zaxbys.com/allergen-guide",
  "habitburger":     "https://www.habitburger.com/nutrition/allergen-guide/",
  "peiwei":          "https://www.peiwei.com/nutrition/allergen-guide",
  "freddys":         "https://www.freddysusa.com/nutrition/allergen-guide",
  "portillos":       "https://www.portillos.com/allergen-info/",
  "goldencorral":    "https://www.goldencorral.com/nutrition",
  "elpollolocoo":    "https://www.elpolloloco.com/nutrition/allergen-guide",
};
