/**
 * Known allergen/menu URLs for major restaurant chains.
 * Used to seed the `website` field when OSM/registry data has none.
 * Keys are lowercase normalized chain names.
 */
export const CHAIN_ALLERGEN_URLS: Record<string, string> = {
  "mcdonald's":              "https://www.mcdonalds.com/us/en-us/about-our-food/nutrition-calculator.html",
  "mcdonalds":               "https://www.mcdonalds.com/us/en-us/about-our-food/nutrition-calculator.html",
  "chipotle mexican grill":  "https://www.chipotle.com/allergen-info",
  "chipotle":                "https://www.chipotle.com/allergen-info",
  "chick-fil-a":             "https://www.chick-fil-a.com/menu",
  "chick fil a":             "https://www.chick-fil-a.com/menu",
  "starbucks":               "https://www.starbucks.com/menu",
  "subway":                  "https://www.subway.com/en-US/menunutrition/nutrition",
  "taco bell":               "https://www.tacobell.com/nutrition/allergens",
  "burger king":             "https://www.bk.com/allergen-information",
  "wendy's":                 "https://www.wendys.com/nutrition",
  "wendys":                  "https://www.wendys.com/nutrition",
  "kfc":                     "https://www.kfc.com/nutrition",
  "domino's":                "https://www.dominos.com/en/pages/content/nutritional/allergens.html",
  "dominos":                 "https://www.dominos.com/en/pages/content/nutritional/allergens.html",
  "domino's pizza":          "https://www.dominos.com/en/pages/content/nutritional/allergens.html",
  "pizza hut":               "https://www.pizzahut.com/calories",
  "panera bread":            "https://www.panerabread.com/en-us/app/menu/allergen-information.html",
  "panera":                  "https://www.panerabread.com/en-us/app/menu/allergen-information.html",
  "dunkin'":                 "https://www.dunkindonuts.com/en/food-drinks/allergen-information",
  "dunkin":                  "https://www.dunkindonuts.com/en/food-drinks/allergen-information",
  "dunkin' donuts":          "https://www.dunkindonuts.com/en/food-drinks/allergen-information",
  "dunkin donuts":           "https://www.dunkindonuts.com/en/food-drinks/allergen-information",
  "five guys":               "https://www.fiveguys.com/fans/toppings",
  "popeyes":                 "https://www.popeyes.com/allergen-information",
  "popeyes louisiana kitchen": "https://www.popeyes.com/allergen-information",
  "shake shack":             "https://www.shakeshack.com/allergen-guide",
  "outback steakhouse":      "https://www.outback.com/menu",
  "outback":                 "https://www.outback.com/menu",
  "applebee's":              "https://www.applebees.com/en/menu",
  "applebees":               "https://www.applebees.com/en/menu",
  "applebee's grill + bar":  "https://www.applebees.com/en/menu",
  "olive garden":            "https://www.olivegarden.com/menu-listing/lunch-dinner",
  "olive garden italian restaurant": "https://www.olivegarden.com/menu-listing/lunch-dinner",
  "chili's":                 "https://www.chilis.com/menu",
  "chili's grill & bar":     "https://www.chilis.com/menu",
  "chilies":                 "https://www.chilis.com/menu",
  "ihop":                    "https://www.ihop.com/en/menu/allergen-info",
  "denny's":                 "https://www.dennys.com/food/allergen-info",
  "dennys":                  "https://www.dennys.com/food/allergen-info",
  "buffalo wild wings":      "https://www.buffalowildwings.com/en/allergen-information",
  "sonic":                   "https://www.sonicdrivein.com/menu/allergens",
  "sonic drive-in":          "https://www.sonicdrivein.com/menu/allergens",
  "arby's":                  "https://www.arbys.com/full-menu/allergens",
  "arbys":                   "https://www.arbys.com/full-menu/allergens",
  "dairy queen":             "https://www.dairyqueen.com/en-us/menu/allergen-info",
  "papa john's":             "https://www.papajohns.com/order/allergen-information.html",
  "papa johns":              "https://www.papajohns.com/order/allergen-information.html",
  "papa john's pizza":       "https://www.papajohns.com/order/allergen-information.html",
  "jimmy john's":            "https://www.jimmyjohns.com/menu/allergens/",
  "jimmy johns":             "https://www.jimmyjohns.com/menu/allergens/",
  "jersey mike's":           "https://www.jerseymikes.com/menu/subs",
  "jersey mikes":            "https://www.jerseymikes.com/menu/subs",
  "jersey mike's subs":      "https://www.jerseymikes.com/menu/subs",
  "hooters":                 "https://www.hooters.com/menu",
  "bonefish grill":          "https://www.bonefishgrill.com/menu",
  "red robin":               "https://www.redrobin.com/allergen-information.html",
  "red robin gourmet burgers": "https://www.redrobin.com/allergen-information.html",
  "wingstop":                "https://www.wingstop.com/allergen-info",
  "raising cane's":          "https://www.raisingcanes.com/menu",
  "raising cane's chicken fingers": "https://www.raisingcanes.com/menu",
  "raising canes":           "https://www.raisingcanes.com/menu",
  "whataburger":             "https://www.whataburger.com/menu/allergen-info",
  "in-n-out burger":         "https://www.in-n-out.com/menu/nutrition",
  "in-n-out":                "https://www.in-n-out.com/menu/nutrition",
  "culver's":                "https://www.culvers.com/nutrition-allergens/allergens",
  "culvers":                 "https://www.culvers.com/nutrition-allergens/allergens",
  "steak 'n shake":          "https://www.steaknshake.com/menu",
  "steak n shake":           "https://www.steaknshake.com/menu",
  "panda express":           "https://www.pandaexpress.com/menu/allergens",
  "little caesars":          "https://littlecaesars.com/en-us/menu/allergen-information/",
  "little caesar's":         "https://littlecaesars.com/en-us/menu/allergen-information/",
  "little caesars pizza":    "https://littlecaesars.com/en-us/menu/allergen-information/",
  "cicis":                   "https://cicis.com/menu",
  "cici's":                  "https://cicis.com/menu",
  "cici's pizza":            "https://cicis.com/menu",
  "jack in the box":         "https://www.jackinthebox.com/food-allergens",
  "moe's southwest grill":   "https://www.moes.com/menu",
  "moes southwest grill":    "https://www.moes.com/menu",
  "qdoba":                   "https://www.qdoba.com/menu/allergen-information",
  "qdoba mexican eats":      "https://www.qdoba.com/menu/allergen-information",
  "el pollo loco":           "https://www.elpolloloco.com/food/allergens/",
  "golden corral":           "https://www.goldencorral.com/",
  "smashburger":             "https://smashburger.com/menu/",
  "noodles & company":       "https://www.noodles.com/menu/allergen-information",
  "noodles and company":     "https://www.noodles.com/menu/allergen-information",
  "p.f. chang's":            "https://www.pfchangs.com/menu",
  "pf changs":               "https://www.pfchangs.com/menu",
  "longhorn steakhouse":     "https://www.longhornsteakhouse.com/menu",
  "texas roadhouse":         "https://www.texasroadhouse.com/menu",
  "red lobster":             "https://www.redlobster.com/allergen",
  "the cheesecake factory":  "https://www.thecheesecakefactory.com/menu",
  "cheesecake factory":      "https://www.thecheesecakefactory.com/menu",
  "perkins":                 "https://www.perkinsrestaurants.com/menu",
  "bob evans":               "https://www.bobevans.com/menu",
  "cracker barrel":          "https://www.crackerbarrel.com/menu",
  "cracker barrel old country store": "https://www.crackerbarrel.com/menu",
  "ihop restaurant":         "https://www.ihop.com/en/menu/allergen-info",
  "waffle house":            "https://www.wafflehouse.com/menu",
  "el azteca":               "https://www.elaztecamexicanrestaurant.com/",
  "yard house":              "https://www.yardhouse.com/menu",
  "bj's restaurants":        "https://www.bjsrestaurants.com/menu",
  "bj's brewhouse":          "https://www.bjsrestaurants.com/menu",
  "mod pizza":               "https://modpizza.com/build-your-pizza/",
  "habit burger":            "https://www.habitburger.com/menu/",
  "the habit burger grill":  "https://www.habitburger.com/menu/",
  "freddy's":                "https://www.freddysusa.com/menu",
  "freddy's frozen custard": "https://www.freddysusa.com/menu",
  "portillo's":              "https://www.portillos.com/menu/allergen-info",
  "hardee's":                "https://www.hardees.com/menu/allergen-information",
  "hardees":                 "https://www.hardees.com/menu/allergen-information",
  "carl's jr":               "https://www.carlsjr.com/menu/allergen-information",
  "church's chicken":        "https://www.churchs.com/menu",
  "zaxby's":                 "https://www.zaxbys.com/nutrition",
  "bojangles":               "https://www.bojangles.com/menu",
};

/** Return the known allergen URL for a restaurant name, or undefined if unknown. */
export function getChainUrl(displayName: string): string | undefined {
  const key = displayName.toLowerCase().trim();
  if (CHAIN_ALLERGEN_URLS[key]) return CHAIN_ALLERGEN_URLS[key];
  // Partial match for names like "McDonald's #4521" or "Subway (Marco Island)"
  for (const [chain, url] of Object.entries(CHAIN_ALLERGEN_URLS)) {
    if (key.startsWith(chain) || key.includes(chain)) return url;
  }
  return undefined;
}
